-- ============================================
-- MODULO AUDITORIA
-- AUTORES: SEBASTIAN SOLANO
-- FECHA: DICIEMBRE 2025
-- ============================================

-- ===============================================
-- 1. CREAR TABLA y SECUENCIA DE AUDITORÍA
-- ===============================================
CREATE TABLE FIDE_AUDITORIA_TB (
    ID_AUDITORIA NUMBER PRIMARY KEY,
    NOMBRE_TABLA VARCHAR2(100),
    ACCION VARCHAR2(20),
    FECHA_ACCION TIMESTAMP,
    USUARIO VARCHAR2(100)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
ALTER TABLE FIDE_AUDITORIA_TB ADD ID_REGISTRO NUMBER;

CREATE SEQUENCE FIDE_AUDITORIA_TB_ID_SEQ 
    START WITH 1 
    INCREMENT BY 1 
    NOCACHE;

-- ===============================================
-- 2. VISTAS DE AUDITORÍA 
-- ==============================================

-- VISTA 1: AUDITORÍA DE PERSONAS
CREATE OR REPLACE VIEW FIDE_AUDITORIA_PERSONAS_V AS
SELECT
    A.ID_AUDITORIA,
    A.ACCION,
    A.FECHA_ACCION,
    A.USUARIO,
    P.CEDULA,
    P.NOMBRE,
    P.APELLIDO_PATERNO,
    P.APELLIDO_MATERNO,
    P.FECHA_CREACION,
    P.FECHA_MODIFICACION,
    P.CREADO_POR,
    P.MODIFICADO_POR
FROM FIDE_AUDITORIA_TB A
JOIN FIDE_PERSONA_TB P 
    ON A.ID_REGISTRO = P.CEDULA
WHERE A.NOMBRE_TABLA = 'FIDE_PERSONA_TB'
ORDER BY A.ID_AUDITORIA DESC;
/

-- VISTA 2: AUDITORÍA DE INFANTES
CREATE OR REPLACE VIEW FIDE_AUDITORIA_INFANTES_V AS
SELECT
    A.ID_AUDITORIA,
    A.ACCION,
    A.FECHA_ACCION,
    A.USUARIO,

    I.CEDULA_INFANTE,
    I.NOMBRE,
    I.APELLIDO_PATERNO,
    I.APELLIDO_MATERNO,
    I.FECHA_CREACION,
    I.FECHA_MODIFICACION,
    I.CREADO_POR,
    I.MODIFICADO_POR

FROM FIDE_AUDITORIA_TB A
JOIN FIDE_INFANTE_TB I 
    ON A.ID_REGISTRO = I.CEDULA_INFANTE
WHERE A.NOMBRE_TABLA = 'FIDE_INFANTE_TB'
ORDER BY A.ID_AUDITORIA DESC;

-- VISTA 3: AUDITORÍA DE FACTURAS
CREATE OR REPLACE VIEW FIDE_AUDITORIA_FACTURAS_V AS
SELECT
    A.ID_AUDITORIA,
    A.ACCION,
    A.FECHA_ACCION,
    A.USUARIO,
    F.ID_FACTURA,
    F.CEDULA,
    F.CEDULA_INFANTE,
    F.MONTO_TOTAL,
    F.FECHA_CREACION,
    F.FECHA_MODIFICACION,
    F.CREADO_POR,
    F.MODIFICADO_POR
FROM FIDE_AUDITORIA_TB A
JOIN FIDE_ENCABEZADO_FACTURA_TB F 
    ON A.ID_REGISTRO = F.ID_FACTURA
WHERE A.NOMBRE_TABLA = 'FIDE_ENCABEZADO_FACTURA_TB'
ORDER BY A.ID_AUDITORIA DESC;
/
--VISTA 4 — MATRÍCULAS 
CREATE OR REPLACE VIEW FIDE_AUDITORIA_MATRICULAS_V AS
SELECT
    A.ID_AUDITORIA,
    A.ACCION,
    A.FECHA_ACCION,
    A.USUARIO,
    M.ID_MATRICULA,
    M.CEDULA,
    M.CEDULA_INFANTE,
    M.FECHA_MATRICULA,
    M.FECHA_CREACION,
    M.FECHA_MODIFICACION,
    M.CREADO_POR,
    M.MODIFICADO_POR
FROM FIDE_AUDITORIA_TB A
JOIN FIDE_MATRICULA_TB M 
    ON A.ID_REGISTRO = M.ID_MATRICULA
WHERE A.NOMBRE_TABLA = 'FIDE_MATRICULA_TB'
ORDER BY A.ID_AUDITORIA DESC;
/
--VISTA 5 — ACTIVIDADES 
CREATE OR REPLACE VIEW FIDE_AUDITORIA_ACTIVIDADES_V AS
SELECT
    A.ID_AUDITORIA,
    A.ACCION,
    A.FECHA_ACCION,
    A.USUARIO,
    AC.ID_ACTIVIDAD,
    AC.DESCRIPCION,
    AC.FECHA,
    AC.HORA,
    AC.FECHA_CREACION,
    AC.FECHA_MODIFICACION,
    AC.CREADO_POR,
    AC.MODIFICADO_POR
FROM FIDE_AUDITORIA_TB A
JOIN FIDE_ACTIVIDAD_TB AC 
    ON A.ID_REGISTRO = AC.ID_ACTIVIDAD
WHERE A.NOMBRE_TABLA = 'FIDE_ACTIVIDAD_TB'
ORDER BY A.ID_AUDITORIA DESC;
/

--VISTA 6 — PAGOS 
CREATE OR REPLACE VIEW FIDE_AUDITORIA_PAGOS_V AS
SELECT
    A.ID_AUDITORIA,
    A.ACCION,
    A.FECHA_ACCION,
    A.USUARIO,
    P.ID_PAGO,
    P.ID_FACTURA,
    P.MONTO_TOTAL,
    P.FECHA_CREACION,
    P.FECHA_MODIFICACION,
    P.CREADO_POR,
    P.MODIFICADO_POR
FROM FIDE_AUDITORIA_TB A
JOIN FIDE_PAGO_TB P 
    ON A.ID_REGISTRO = P.ID_PAGO
WHERE A.NOMBRE_TABLA = 'FIDE_PAGO_TB'
ORDER BY A.ID_AUDITORIA DESC;
/

