--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-10-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package FIDE_PROYECTO_LBD_PCK
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "PROYECTO_LBD"."FIDE_PROYECTO_LBD_PCK" AS 
----------------------------------------------------------------------------------------------------------
-- FUNCIONES
FUNCTION FIDE_VALIDAR_FACTURA_PARA_MATRICULA_FN (
    P_ID_FACTURA IN NUMBER
) RETURN NUMBER;
------------------------------------------------------
FUNCTION FIDE_VALIDAR_FACTURA_PARA_MENSUALIDAD_FN (
    P_ID_FACTURA IN NUMBER
) RETURN NUMBER;
------------------------------------------------------
FUNCTION FIDE_VALIDAR_CEDULA_PERSONA_FN (
    P_CEDULA IN NUMBER
) RETURN NUMBER;
------------------------------------------------------
FUNCTION FIDE_VALIDAR_CEDULA_INFANTE_FN (
    P_CEDULA_INFANTE IN NUMBER
) RETURN NUMBER;
------------------------------------------------------
FUNCTION FIDE_CONTAR_INFANTES_MATRICULADOS_FN
RETURN NUMBER;
------------------------------------------------------
FUNCTION FIDE_CONTAR_INFANTES_POR_GRUPO_FN (
    P_ID_GRUPO IN NUMBER
) RETURN NUMBER;
------------------------------------------------------
FUNCTION FIDE_CONTAR_ACTIVIDADES_GRUPO_FN (
    P_ID_GRUPO IN NUMBER
) RETURN NUMBER;
------------------------------------------------------
FUNCTION FIDE_CONTAR_TUTORES_INFANTE_FN (
    P_CEDULA_INFANTE IN NUMBER
) RETURN NUMBER;
------------------------------------------------------
FUNCTION FIDE_CONTAR_TOTAL_INFANTES_FN
RETURN NUMBER;
------------------------------------------------------
FUNCTION FIDE_CONTAR_TOTAL_ADMINISTRADORES_FN
RETURN NUMBER;
------------------------------------------------------
FUNCTION FIDE_CONTAR_TOTAL_DOCENTES_FN
RETURN NUMBER;
------------------------------------------------------
FUNCTION FIDE_CONTAR_TOTAL_APODERADOS_FN
RETURN NUMBER;
------------------------------------------------------
FUNCTION FIDE_CONTAR_TOTAL_GRUPOS_FN
RETURN NUMBER;
------------------------------------------------------
FUNCTION FIDE_TOTAL_ASISTENCIA_HOY_FN
RETURN NUMBER;
------------------------------------------------------
FUNCTION FIDE_TOTAL_FACTURAS_HOY_FN
RETURN NUMBER;
----------------------------------------------------------------------------------------------------------
-- PROCEDIMIENTOS
PROCEDURE FIDE_ESTADO_INSERT_SP(
    P_ID_ESTADO IN FIDE_ESTADO_TB.ID_ESTADO%TYPE,
    P_DESCRIPCION IN FIDE_ESTADO_TB.DESCRIPCION%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ESTADO_UPDATE_SP(
    P_ID_ESTADO IN FIDE_ESTADO_TB.ID_ESTADO%TYPE,
    P_DESCRIPCION IN FIDE_ESTADO_TB.DESCRIPCION%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PAIS_INSERT_SP(
    P_ID_PAIS IN FIDE_PAIS_TB.ID_PAIS%TYPE,
    P_NOMBRE IN FIDE_PAIS_TB.NOMBRE%TYPE,
    P_ID_ESTADO IN FIDE_PAIS_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PAIS_UPDATE_SP(
    P_ID_PAIS IN FIDE_PAIS_TB.ID_PAIS%TYPE,
    P_NOMBRE IN FIDE_PAIS_TB.NOMBRE%TYPE,
    P_ID_ESTADO IN FIDE_PAIS_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PAIS_DELETE_SP(
    P_ID_PAIS IN FIDE_PAIS_TB.ID_PAIS%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PROVINCIA_INSERT_SP(
    P_ID_PROVINCIA IN FIDE_PROVINCIA_TB.ID_PROVINCIA%TYPE,
    P_NOMBRE IN FIDE_PROVINCIA_TB.NOMBRE%TYPE,
    P_ID_ESTADO IN FIDE_PROVINCIA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PROVINCIA_UPDATE_SP(
    P_ID_PROVINCIA IN FIDE_PROVINCIA_TB.ID_PROVINCIA%TYPE,
    P_NOMBRE IN FIDE_PROVINCIA_TB.NOMBRE%TYPE,
    P_ID_ESTADO IN FIDE_PROVINCIA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PROVINCIA_DELETE_SP(
    P_ID_PROVINCIA IN FIDE_PROVINCIA_TB.ID_PROVINCIA%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CANTON_INSERT_SP(
    P_ID_CANTON IN FIDE_CANTON_TB.ID_CANTON%TYPE,
    P_NOMBRE IN FIDE_CANTON_TB.NOMBRE%TYPE,
    P_ID_ESTADO IN FIDE_CANTON_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CANTON_UPDATE_SP(
    P_ID_CANTON IN FIDE_CANTON_TB.ID_CANTON%TYPE,
    P_NOMBRE IN FIDE_CANTON_TB.NOMBRE%TYPE,
    P_ID_ESTADO IN FIDE_CANTON_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CANTON_DELETE_SP(
    P_ID_CANTON IN FIDE_CANTON_TB.ID_CANTON%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_DISTRITO_INSERT_SP(
    P_ID_DISTRITO IN FIDE_DISTRITO_TB.ID_DISTRITO%TYPE,
    P_NOMBRE IN FIDE_DISTRITO_TB.NOMBRE%TYPE,
    P_ID_ESTADO IN FIDE_DISTRITO_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_DISTRITO_UPDATE_SP(
    P_ID_DISTRITO IN FIDE_DISTRITO_TB.ID_DISTRITO%TYPE,
    P_NOMBRE IN FIDE_DISTRITO_TB.NOMBRE%TYPE,
    P_ID_ESTADO IN FIDE_DISTRITO_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_DISTRITO_DELETE_SP(
    P_ID_DISTRITO IN FIDE_DISTRITO_TB.ID_DISTRITO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ROL_INSERT_SP(
    P_ID_ROL IN FIDE_ROL_TB.ID_ROL%TYPE,
    P_NOMBRE IN FIDE_ROL_TB.NOMBRE%TYPE,
    P_ID_ESTADO IN FIDE_ROL_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ROL_UPDATE_SP(
    P_ID_ROL IN FIDE_ROL_TB.ID_ROL%TYPE,
    P_NOMBRE IN FIDE_ROL_TB.NOMBRE%TYPE,
    P_ID_ESTADO IN FIDE_ROL_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ROL_DELETE_SP(
    P_ID_ROL IN FIDE_ROL_TB.ID_ROL%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PERSONA_INSERT_SP(
    P_CEDULA IN FIDE_PERSONA_TB.CEDULA%TYPE,
    P_NOMBRE IN FIDE_PERSONA_TB.NOMBRE%TYPE,
    P_APELLIDO_PATERNO IN FIDE_PERSONA_TB.APELLIDO_PATERNO%TYPE,
    P_APELLIDO_MATERNO IN FIDE_PERSONA_TB.APELLIDO_MATERNO%TYPE,
    P_FECHA_NACIMIENTO IN FIDE_PERSONA_TB.FECHA_NACIMIENTO%TYPE,
    P_ID_ROL IN FIDE_PERSONA_TB.ID_ROL%TYPE,
    P_ID_ESTADO IN FIDE_PERSONA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PERSONA_UPDATE_SP(
    P_CEDULA IN FIDE_PERSONA_TB.CEDULA%TYPE,
    P_NOMBRE IN FIDE_PERSONA_TB.NOMBRE%TYPE,
    P_APELLIDO_PATERNO IN FIDE_PERSONA_TB.APELLIDO_PATERNO%TYPE,
    P_APELLIDO_MATERNO IN FIDE_PERSONA_TB.APELLIDO_MATERNO%TYPE,
    P_FECHA_NACIMIENTO IN FIDE_PERSONA_TB.FECHA_NACIMIENTO%TYPE,
    P_ID_ROL IN FIDE_PERSONA_TB.ID_ROL%TYPE,
    P_ID_ESTADO IN FIDE_PERSONA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PERSONA_DELETE_SP(
    P_CEDULA IN FIDE_PERSONA_TB.CEDULA%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_DIRECCION_INSERT_SP(
    P_CEDULA IN FIDE_DIRECCION_TB.CEDULA%TYPE,
    P_ID_PAIS IN FIDE_DIRECCION_TB.ID_PAIS%TYPE,
    P_ID_PROVINCIA IN FIDE_DIRECCION_TB.ID_PROVINCIA%TYPE,
    P_ID_CANTON IN FIDE_DIRECCION_TB.ID_CANTON%TYPE,
    P_ID_DISTRITO IN FIDE_DIRECCION_TB.ID_DISTRITO%TYPE,
    P_OTRAS_SENAS IN FIDE_DIRECCION_TB.OTRAS_SENAS%TYPE,
    P_ID_ESTADO IN FIDE_DIRECCION_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_DIRECCION_UPDATE_SP(
    P_CEDULA IN FIDE_DIRECCION_TB.CEDULA%TYPE,
    P_ID_PAIS IN FIDE_DIRECCION_TB.ID_PAIS%TYPE,
    P_ID_PROVINCIA IN FIDE_DIRECCION_TB.ID_PROVINCIA%TYPE,
    P_ID_CANTON IN FIDE_DIRECCION_TB.ID_CANTON%TYPE,
    P_ID_DISTRITO IN FIDE_DIRECCION_TB.ID_DISTRITO%TYPE,
    P_OTRAS_SENAS IN FIDE_DIRECCION_TB.OTRAS_SENAS%TYPE,
    P_ID_ESTADO IN FIDE_DIRECCION_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_DIRECCION_DELETE_SP(
    P_CEDULA IN FIDE_DIRECCION_TB.CEDULA%TYPE,
    P_ID_PAIS IN FIDE_DIRECCION_TB.ID_PAIS%TYPE,
    P_ID_PROVINCIA IN FIDE_DIRECCION_TB.ID_PROVINCIA%TYPE,
    P_ID_CANTON IN FIDE_DIRECCION_TB.ID_CANTON%TYPE,
    P_ID_DISTRITO IN FIDE_DIRECCION_TB.ID_DISTRITO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_USUARIO_INSERT_SP(
    P_CEDULA IN FIDE_USUARIO_TB.CEDULA%TYPE,
    P_USERNAME IN FIDE_USUARIO_TB.USERNAME%TYPE,
    P_CONTRASENA IN FIDE_USUARIO_TB.CONTRASENA%TYPE,
    P_ID_ESTADO IN FIDE_USUARIO_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_USUARIO_UPDATE_SP(
    P_CEDULA IN FIDE_USUARIO_TB.CEDULA%TYPE,
    P_USERNAME IN FIDE_USUARIO_TB.USERNAME%TYPE,
    P_CONTRASENA IN FIDE_USUARIO_TB.CONTRASENA%TYPE,
    P_ID_ESTADO IN FIDE_USUARIO_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_USUARIO_DELETE_SP(
    P_CEDULA IN FIDE_USUARIO_TB.CEDULA%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_EMAIL_INSERT_SP(
    P_CEDULA IN FIDE_EMAIL_TB.CEDULA%TYPE,
    P_EMAIL IN FIDE_EMAIL_TB.EMAIL%TYPE,
    P_ID_ESTADO IN FIDE_EMAIL_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_EMAIL_UPDATE_SP(
    P_CEDULA IN FIDE_EMAIL_TB.CEDULA%TYPE,
    P_EMAIL IN FIDE_EMAIL_TB.EMAIL%TYPE,
    P_ID_ESTADO IN FIDE_EMAIL_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_EMAIL_DELETE_SP(
    P_CEDULA IN FIDE_EMAIL_TB.CEDULA%TYPE,
    P_EMAIL IN FIDE_EMAIL_TB.EMAIL%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_TELEFONO_INSERT_SP(
    P_CEDULA IN FIDE_TELEFONO_TB.CEDULA%TYPE,
    P_NUM_TELEFONO IN FIDE_TELEFONO_TB.NUM_TELEFONO%TYPE,
    P_ID_ESTADO IN FIDE_TELEFONO_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_TELEFONO_UPDATE_SP(
    P_CEDULA IN FIDE_TELEFONO_TB.CEDULA%TYPE,
    P_NUM_TELEFONO IN FIDE_TELEFONO_TB.NUM_TELEFONO%TYPE,
    P_ID_ESTADO IN FIDE_TELEFONO_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_TELEFONO_DELETE_SP(
    P_CEDULA IN FIDE_TELEFONO_TB.CEDULA%TYPE,
    P_NUM_TELEFONO IN FIDE_TELEFONO_TB.NUM_TELEFONO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CATEGORIA_INSERT_SP(
    P_ID_CATEGORIA IN FIDE_CATEGORIA_TB.ID_CATEGORIA%TYPE,
    P_DESCRIPCION IN FIDE_CATEGORIA_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO IN FIDE_CATEGORIA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CATEGORIA_UPDATE_SP(
    P_ID_CATEGORIA IN FIDE_CATEGORIA_TB.ID_CATEGORIA%TYPE,
    P_DESCRIPCION IN FIDE_CATEGORIA_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO IN FIDE_CATEGORIA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CATEGORIA_DELETE_SP(
    P_ID_CATEGORIA IN FIDE_CATEGORIA_TB.ID_CATEGORIA%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_INSTITUCION_INSERT_SP(
    P_ID_INSTITUCION IN FIDE_INSTITUCION_TB.ID_INSTITUCION%TYPE,
    P_NOMBRE IN FIDE_INSTITUCION_TB.NOMBRE%TYPE,
    P_ID_CATEGORIA IN FIDE_INSTITUCION_TB.ID_CATEGORIA%TYPE,
    P_ID_ESTADO IN FIDE_INSTITUCION_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_INSTITUCION_UPDATE_SP(
    P_ID_INSTITUCION IN FIDE_INSTITUCION_TB.ID_INSTITUCION%TYPE,
    P_NOMBRE IN FIDE_INSTITUCION_TB.NOMBRE%TYPE,
    P_ID_CATEGORIA IN FIDE_INSTITUCION_TB.ID_CATEGORIA%TYPE,
    P_ID_ESTADO IN FIDE_INSTITUCION_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_INSTITUCION_DELETE_SP(
    P_ID_INSTITUCION IN FIDE_INSTITUCION_TB.ID_INSTITUCION%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_FORMACION_ACADEMICA_TB_INSERT_SP(
    P_ID_FORMACION IN FIDE_FORMACION_ACADEMICA_TB.ID_FORMACION%TYPE,
    P_CEDULA IN FIDE_FORMACION_ACADEMICA_TB.CEDULA%TYPE,
    P_ID_INSTITUCION IN FIDE_FORMACION_ACADEMICA_TB.ID_INSTITUCION%TYPE,
    P_TITULO IN FIDE_FORMACION_ACADEMICA_TB.TITULO%TYPE,
    P_FECHA_OBTENCION IN FIDE_FORMACION_ACADEMICA_TB.FECHA_OBTENCION%TYPE,
    P_ID_ESTADO IN FIDE_FORMACION_ACADEMICA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_FORMACION_ACADEMICA_TB_UPDATE_SP(
    P_ID_FORMACION IN FIDE_FORMACION_ACADEMICA_TB.ID_FORMACION%TYPE,
    P_CEDULA IN FIDE_FORMACION_ACADEMICA_TB.CEDULA%TYPE,
    P_ID_INSTITUCION IN FIDE_FORMACION_ACADEMICA_TB.ID_INSTITUCION%TYPE,
    P_TITULO IN FIDE_FORMACION_ACADEMICA_TB.TITULO%TYPE,
    P_FECHA_OBTENCION IN FIDE_FORMACION_ACADEMICA_TB.FECHA_OBTENCION%TYPE,
    P_ID_ESTADO IN FIDE_FORMACION_ACADEMICA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_FORMACION_ACADEMICA_TB_DELETE_SP(
    P_ID_FORMACION IN FIDE_FORMACION_ACADEMICA_TB.ID_FORMACION%TYPE,
    P_CEDULA IN FIDE_FORMACION_ACADEMICA_TB.CEDULA%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_TEMA_INSERT_SP(
    P_ID_TEMA IN FIDE_TEMA_TB.ID_TEMA%TYPE,
    P_DESCRIPCION IN FIDE_TEMA_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO IN FIDE_TEMA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_TEMA_UPDATE_SP(
    P_ID_TEMA IN FIDE_TEMA_TB.ID_TEMA%TYPE,
    P_DESCRIPCION IN FIDE_TEMA_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO IN FIDE_TEMA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_TEMA_DELETE_SP(
    P_ID_TEMA IN FIDE_TEMA_TB.ID_TEMA%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PROVEEDOR_INSERT_SP(
    P_ID_PROVEEDOR IN FIDE_PROVEEDOR_TB.ID_PROVEEDOR%TYPE,
    P_DESCRIPCION IN FIDE_PROVEEDOR_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO IN FIDE_PROVEEDOR_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PROVEEDOR_UPDATE_SP(
    P_ID_PROVEEDOR IN FIDE_PROVEEDOR_TB.ID_PROVEEDOR%TYPE,
    P_DESCRIPCION IN FIDE_PROVEEDOR_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO IN FIDE_PROVEEDOR_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PROVEEDOR_DELETE_SP(
    P_ID_PROVEEDOR IN FIDE_PROVEEDOR_TB.ID_PROVEEDOR%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CAPACITACION_INSERT_SP(
    P_CEDULA IN FIDE_CAPACITACION_TB.CEDULA%TYPE,
    P_ID_TEMA IN FIDE_CAPACITACION_TB.ID_TEMA%TYPE,
    P_ID_PROVEEDOR IN FIDE_CAPACITACION_TB.ID_PROVEEDOR%TYPE,
    P_ANIO IN FIDE_CAPACITACION_TB.ANIO%TYPE,
    P_HORAS IN FIDE_CAPACITACION_TB.HORAS%TYPE,
    P_ID_ESTADO IN FIDE_CAPACITACION_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CAPACITACION_UPDATE_SP(
    P_CEDULA IN FIDE_CAPACITACION_TB.CEDULA%TYPE,
    P_ID_TEMA IN FIDE_CAPACITACION_TB.ID_TEMA%TYPE,
    P_ID_PROVEEDOR IN FIDE_CAPACITACION_TB.ID_PROVEEDOR%TYPE,
    P_ANIO IN FIDE_CAPACITACION_TB.ANIO%TYPE,
    P_HORAS IN FIDE_CAPACITACION_TB.HORAS%TYPE,
    P_ID_ESTADO IN FIDE_CAPACITACION_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CAPACITACION_DELETE_SP(
    P_CEDULA IN FIDE_CAPACITACION_TB.CEDULA%TYPE,
    P_ID_TEMA IN FIDE_CAPACITACION_TB.ID_TEMA%TYPE,
    P_ID_PROVEEDOR IN FIDE_CAPACITACION_TB.ID_PROVEEDOR%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_EMPRESA_INSERT_SP(
    P_ID_EMPRESA IN FIDE_EMPRESA_TB.ID_EMPRESA%TYPE,
    P_DESCRIPCION IN FIDE_EMPRESA_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO IN FIDE_EMPRESA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_EMPRESA_UPDATE_SP(
    P_ID_EMPRESA IN FIDE_EMPRESA_TB.ID_EMPRESA%TYPE,
    P_DESCRIPCION IN FIDE_EMPRESA_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO IN FIDE_EMPRESA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_EMPRESA_DELETE_SP(
    P_ID_EMPRESA IN FIDE_EMPRESA_TB.ID_EMPRESA%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CARGO_INSERT_SP(
    P_ID_CARGO IN FIDE_CARGO_TB.ID_CARGO%TYPE,
    P_DESCRIPCION IN FIDE_CARGO_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO IN FIDE_CARGO_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CARGO_UPDATE_SP(
    P_ID_CARGO IN FIDE_CARGO_TB.ID_CARGO%TYPE,
    P_DESCRIPCION IN FIDE_CARGO_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO IN FIDE_CARGO_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CARGO_DELETE_SP(
    P_ID_CARGO IN FIDE_CARGO_TB.ID_CARGO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_EXPERIENCIA_LABORAL_INSERT_SP(
    P_CEDULA IN FIDE_EXPERIENCIA_LABORAL_TB.CEDULA%TYPE,
    P_ID_EMPRESA IN FIDE_EXPERIENCIA_LABORAL_TB.ID_EMPRESA%TYPE,
    P_ID_CARGO IN FIDE_EXPERIENCIA_LABORAL_TB.ID_CARGO%TYPE,
    P_FECHA_INICIO IN FIDE_EXPERIENCIA_LABORAL_TB.FECHA_INICIO%TYPE,
    P_FECHA_FINAL IN FIDE_EXPERIENCIA_LABORAL_TB.FECHA_FINAL%TYPE,
    P_ID_ESTADO IN FIDE_EXPERIENCIA_LABORAL_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_EXPERIENCIA_LABORAL_UPDATE_SP(
    P_CEDULA IN FIDE_EXPERIENCIA_LABORAL_TB.CEDULA%TYPE,
    P_ID_EMPRESA IN FIDE_EXPERIENCIA_LABORAL_TB.ID_EMPRESA%TYPE,
    P_ID_CARGO IN FIDE_EXPERIENCIA_LABORAL_TB.ID_CARGO%TYPE,
    P_FECHA_INICIO IN FIDE_EXPERIENCIA_LABORAL_TB.FECHA_INICIO%TYPE,
    P_FECHA_FINAL IN FIDE_EXPERIENCIA_LABORAL_TB.FECHA_FINAL%TYPE,
    P_ID_ESTADO IN FIDE_EXPERIENCIA_LABORAL_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_EXPERIENCIA_LABORAL_DELETE_SP(
    P_CEDULA IN FIDE_EXPERIENCIA_LABORAL_TB.CEDULA%TYPE,
    P_ID_EMPRESA IN FIDE_EXPERIENCIA_LABORAL_TB.ID_EMPRESA%TYPE,
    P_ID_CARGO IN FIDE_EXPERIENCIA_LABORAL_TB.ID_CARGO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_TIPO_EVALUACION_INSERT_SP(
    P_ID_TIPO_EVALUACION IN FIDE_TIPO_EVALUACION_TB.ID_TIPO_EVALUACION%TYPE,
    P_DESCRIPCION IN FIDE_TIPO_EVALUACION_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO IN FIDE_TIPO_EVALUACION_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_TIPO_EVALUACION_UPDATE_SP(
    P_ID_TIPO_EVALUACION IN FIDE_TIPO_EVALUACION_TB.ID_TIPO_EVALUACION%TYPE,
    P_DESCRIPCION IN FIDE_TIPO_EVALUACION_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO IN FIDE_TIPO_EVALUACION_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_TIPO_EVALUACION_DELETE_SP(
    P_ID_TIPO_EVALUACION IN FIDE_TIPO_EVALUACION_TB.ID_TIPO_EVALUACION%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_EVALUACION_DOCENTE_INSERT_SP(
    P_CEDULA IN FIDE_EVALUACION_DOCENTE_TB.CEDULA%TYPE,
    P_ID_TIPO_EVALUACION IN FIDE_EVALUACION_DOCENTE_TB.ID_TIPO_EVALUACION%TYPE,
    P_ANIO IN FIDE_EVALUACION_DOCENTE_TB.ANIO%TYPE,
    P_CALIFICACION IN FIDE_EVALUACION_DOCENTE_TB.CALIFICACION%TYPE,
    P_COMENTARIOS IN FIDE_EVALUACION_DOCENTE_TB.COMENTARIOS%TYPE,
    P_ID_ESTADO IN FIDE_EVALUACION_DOCENTE_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_EVALUACION_DOCENTE_UPDATE_SP(
    P_CEDULA IN FIDE_EVALUACION_DOCENTE_TB.CEDULA%TYPE,
    P_ID_TIPO_EVALUACION IN FIDE_EVALUACION_DOCENTE_TB.ID_TIPO_EVALUACION%TYPE,
    P_ANIO IN FIDE_EVALUACION_DOCENTE_TB.ANIO%TYPE,
    P_CALIFICACION IN FIDE_EVALUACION_DOCENTE_TB.CALIFICACION%TYPE,
    P_COMENTARIOS IN FIDE_EVALUACION_DOCENTE_TB.COMENTARIOS%TYPE,
    P_ID_ESTADO IN FIDE_EVALUACION_DOCENTE_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_EVALUACION_DOCENTE_DELETE_SP(
    P_CEDULA IN FIDE_EVALUACION_DOCENTE_TB.CEDULA%TYPE,
    P_ID_TIPO_EVALUACION IN FIDE_EVALUACION_DOCENTE_TB.ID_TIPO_EVALUACION%TYPE,
    P_ANIO IN FIDE_EVALUACION_DOCENTE_TB.ANIO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_INFANTE_INSERT_SP(
    P_CEDULA_INFANTE IN FIDE_INFANTE_TB.CEDULA_INFANTE%TYPE,
    P_NOMBRE IN FIDE_INFANTE_TB.NOMBRE%TYPE,
    P_APELLIDO_PATERNO IN FIDE_INFANTE_TB.APELLIDO_PATERNO%TYPE,
    P_APELLIDO_MATERNO IN FIDE_INFANTE_TB.APELLIDO_MATERNO%TYPE,
    P_FECHA_NACIMIENTO IN FIDE_INFANTE_TB.FECHA_NACIMIENTO%TYPE,
    P_ID_ESTADO IN FIDE_INFANTE_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_INFANTE_UPDATE_SP(
    P_CEDULA_INFANTE IN FIDE_INFANTE_TB.CEDULA_INFANTE%TYPE,
    P_NOMBRE IN FIDE_INFANTE_TB.NOMBRE%TYPE,
    P_APELLIDO_PATERNO IN FIDE_INFANTE_TB.APELLIDO_PATERNO%TYPE,
    P_APELLIDO_MATERNO IN FIDE_INFANTE_TB.APELLIDO_MATERNO%TYPE,
    P_FECHA_NACIMIENTO IN FIDE_INFANTE_TB.FECHA_NACIMIENTO%TYPE,
    P_ID_ESTADO IN FIDE_INFANTE_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_INFANTE_DELETE_SP(
    P_CEDULA_INFANTE IN FIDE_INFANTE_TB.CEDULA_INFANTE%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ALERGIA_INSERT_SP(
    P_ID_ALERGIA IN FIDE_ALERGIA_TB.ID_ALERGIA%TYPE,
    P_NOMBRE IN FIDE_ALERGIA_TB.NOMBRE%TYPE,
    P_ID_ESTADO IN FIDE_ALERGIA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ALERGIA_UPDATE_SP(
    P_ID_ALERGIA IN FIDE_ALERGIA_TB.ID_ALERGIA%TYPE,
    P_NOMBRE IN FIDE_ALERGIA_TB.NOMBRE%TYPE,
    P_ID_ESTADO IN FIDE_ALERGIA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ALERGIA_DELETE_SP(
    P_ID_ALERGIA IN FIDE_ALERGIA_TB.ID_ALERGIA%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_VACUNA_INSERT_SP(
    P_ID_VACUNA IN FIDE_VACUNA_TB.ID_VACUNA%TYPE,
    P_TIPO_VACUNA IN FIDE_VACUNA_TB.TIPO_VACUNA%TYPE,
    P_ID_ESTADO IN FIDE_VACUNA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_VACUNA_UPDATE_SP(
    P_ID_VACUNA IN FIDE_VACUNA_TB.ID_VACUNA%TYPE,
    P_TIPO_VACUNA IN FIDE_VACUNA_TB.TIPO_VACUNA%TYPE,
    P_ID_ESTADO IN FIDE_VACUNA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_VACUNA_DELETE_SP(
    P_ID_VACUNA IN FIDE_VACUNA_TB.ID_VACUNA%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_MEDICAMENTO_INSERT_SP(
    P_ID_MEDICAMENTO IN FIDE_MEDICAMENTO_TB.ID_MEDICAMENTO%TYPE,
    P_NOMBRE IN FIDE_MEDICAMENTO_TB.NOMBRE%TYPE,
    P_ID_ESTADO IN FIDE_MEDICAMENTO_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_MEDICAMENTO_UPDATE_SP(
    P_ID_MEDICAMENTO IN FIDE_MEDICAMENTO_TB.ID_MEDICAMENTO%TYPE,
    P_NOMBRE IN FIDE_MEDICAMENTO_TB.NOMBRE%TYPE,
    P_ID_ESTADO IN FIDE_MEDICAMENTO_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_MEDICAMENTO_DELETE_SP(
    P_ID_MEDICAMENTO IN FIDE_MEDICAMENTO_TB.ID_MEDICAMENTO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_TUTORES_INFANTES_INSERT_SP(
    P_CEDULA IN FIDE_TUTORES_INFANTES_TB.CEDULA%TYPE,
    P_CEDULA_INFANTE IN FIDE_TUTORES_INFANTES_TB.CEDULA_INFANTE%TYPE,
    P_ID_ESTADO IN FIDE_TUTORES_INFANTES_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_TUTORES_INFANTES_UPDATE_SP(
    P_CEDULA IN FIDE_TUTORES_INFANTES_TB.CEDULA%TYPE,
    P_CEDULA_INFANTE IN FIDE_TUTORES_INFANTES_TB.CEDULA_INFANTE%TYPE,
    P_ID_ESTADO IN FIDE_TUTORES_INFANTES_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_TUTORES_INFANTES_DELETE_SP(
    P_CEDULA IN FIDE_TUTORES_INFANTES_TB.CEDULA%TYPE,
    P_CEDULA_INFANTE IN FIDE_TUTORES_INFANTES_TB.CEDULA_INFANTE%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ASISTENCIA_INSERT_SP(
    P_CEDULA_INFANTE IN FIDE_ASISTENCIA_TB.CEDULA_INFANTE%TYPE,
    P_FECHA IN FIDE_ASISTENCIA_TB.FECHA%TYPE,
    P_HORA_ENTRADA IN FIDE_ASISTENCIA_TB.HORA_ENTRADA%TYPE,
    P_HORA_SALIDA IN FIDE_ASISTENCIA_TB.HORA_SALIDA%TYPE,
    P_OBSERVACIONES IN FIDE_ASISTENCIA_TB.OBSERVACIONES%TYPE,
    P_ID_ESTADO IN FIDE_ASISTENCIA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ASISTENCIA_UPDATE_SP(
    P_CEDULA_INFANTE IN FIDE_ASISTENCIA_TB.CEDULA_INFANTE%TYPE,
    P_FECHA IN FIDE_ASISTENCIA_TB.FECHA%TYPE,
    P_HORA_ENTRADA IN FIDE_ASISTENCIA_TB.HORA_ENTRADA%TYPE,
    P_HORA_SALIDA IN FIDE_ASISTENCIA_TB.HORA_SALIDA%TYPE,
    P_OBSERVACIONES IN FIDE_ASISTENCIA_TB.OBSERVACIONES%TYPE,
    P_ID_ESTADO IN FIDE_ASISTENCIA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ASISTENCIA_DELETE_SP(
    P_CEDULA_INFANTE IN FIDE_ASISTENCIA_TB.CEDULA_INFANTE%TYPE,
    P_FECHA IN FIDE_ASISTENCIA_TB.FECHA%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_GRUPO_INSERT_SP(
    P_ID_GRUPO IN FIDE_GRUPO_TB.ID_GRUPO%TYPE,
    P_CEDULA IN FIDE_GRUPO_TB.CEDULA%TYPE,
    P_NOMBRE IN FIDE_GRUPO_TB.NOMBRE%TYPE,
    P_ID_ESTADO IN FIDE_GRUPO_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_GRUPO_UPDATE_SP(
    P_ID_GRUPO IN FIDE_GRUPO_TB.ID_GRUPO%TYPE,
    P_CEDULA IN FIDE_GRUPO_TB.CEDULA%TYPE,
    P_NOMBRE IN FIDE_GRUPO_TB.NOMBRE%TYPE,
    P_ID_ESTADO IN FIDE_GRUPO_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_GRUPO_DELETE_SP(
    P_ID_GRUPO IN FIDE_GRUPO_TB.ID_GRUPO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_DETALLE_GRUPO_INSERT_SP(
    P_ID_GRUPO IN FIDE_DETALLE_GRUPO_TB.ID_GRUPO%TYPE,
    P_CEDULA_INFANTE IN FIDE_DETALLE_GRUPO_TB.CEDULA_INFANTE%TYPE,
    P_ID_ESTADO IN FIDE_DETALLE_GRUPO_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_DETALLE_GRUPO_UPDATE_SP(
    P_ID_GRUPO IN FIDE_DETALLE_GRUPO_TB.ID_GRUPO%TYPE,
    P_CEDULA_INFANTE IN FIDE_DETALLE_GRUPO_TB.CEDULA_INFANTE%TYPE,
    P_ID_ESTADO IN FIDE_DETALLE_GRUPO_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_DETALLE_GRUPO_DELETE_SP(
    P_ID_GRUPO IN FIDE_DETALLE_GRUPO_TB.ID_GRUPO%TYPE,
    P_CEDULA_INFANTE IN FIDE_DETALLE_GRUPO_TB.CEDULA_INFANTE%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_INFANTES_ALERGIAS_INSERT_SP(
    P_CEDULA_INFANTE IN FIDE_INFANTES_ALERGIAS_TB.CEDULA_INFANTE%TYPE,
    P_ID_ALERGIA IN FIDE_INFANTES_ALERGIAS_TB.ID_ALERGIA%TYPE,
    P_OBSERVACION IN FIDE_INFANTES_ALERGIAS_TB.OBSERVACION%TYPE,
    P_SEVERIDAD IN FIDE_INFANTES_ALERGIAS_TB.SEVERIDAD%TYPE,
    P_ID_ESTADO IN FIDE_INFANTES_ALERGIAS_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_INFANTES_ALERGIAS_UPDATE_SP(
    P_CEDULA_INFANTE IN FIDE_INFANTES_ALERGIAS_TB.CEDULA_INFANTE%TYPE,
    P_ID_ALERGIA IN FIDE_INFANTES_ALERGIAS_TB.ID_ALERGIA%TYPE,
    P_OBSERVACION IN FIDE_INFANTES_ALERGIAS_TB.OBSERVACION%TYPE,
    P_SEVERIDAD IN FIDE_INFANTES_ALERGIAS_TB.SEVERIDAD%TYPE,
    P_ID_ESTADO IN FIDE_INFANTES_ALERGIAS_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_INFANTES_ALERGIAS_DELETE_SP(
    P_CEDULA_INFANTE IN FIDE_INFANTES_ALERGIAS_TB.CEDULA_INFANTE%TYPE,
    P_ID_ALERGIA IN FIDE_INFANTES_ALERGIAS_TB.ID_ALERGIA%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_INFANTES_VACUNAS_INSERT_SP(
    P_CEDULA_INFANTE IN FIDE_INFANTES_VACUNAS_TB.CEDULA_INFANTE%TYPE,
    P_ID_VACUNA IN FIDE_INFANTES_VACUNAS_TB.ID_VACUNA%TYPE,
    P_FECHA IN FIDE_INFANTES_VACUNAS_TB.FECHA%TYPE,
    P_ID_ESTADO IN FIDE_INFANTES_VACUNAS_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_INFANTES_VACUNAS_UPDATE_SP(
    P_CEDULA_INFANTE IN FIDE_INFANTES_VACUNAS_TB.CEDULA_INFANTE%TYPE,
    P_ID_VACUNA IN FIDE_INFANTES_VACUNAS_TB.ID_VACUNA%TYPE,
    P_FECHA IN FIDE_INFANTES_VACUNAS_TB.FECHA%TYPE,
    P_ID_ESTADO IN FIDE_INFANTES_VACUNAS_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_INFANTES_VACUNAS_DELETE_SP(
    P_CEDULA_INFANTE IN FIDE_INFANTES_VACUNAS_TB.CEDULA_INFANTE%TYPE,
    P_ID_VACUNA IN FIDE_INFANTES_VACUNAS_TB.ID_VACUNA%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_INFANTES_MEDICAMENTOS_INSERT_SP(
    P_CEDULA_INFANTE IN FIDE_INFANTES_MEDICAMENTOS_TB.CEDULA_INFANTE%TYPE,
    P_ID_MEDICAMENTO IN FIDE_INFANTES_MEDICAMENTOS_TB.ID_MEDICAMENTO%TYPE,
    P_DOSIS IN FIDE_INFANTES_MEDICAMENTOS_TB.DOSIS%TYPE,
    P_ID_ESTADO IN FIDE_INFANTES_MEDICAMENTOS_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_INFANTES_MEDICAMENTOS_UPDATE_SP(
    P_CEDULA_INFANTE IN FIDE_INFANTES_MEDICAMENTOS_TB.CEDULA_INFANTE%TYPE,
    P_ID_MEDICAMENTO IN FIDE_INFANTES_MEDICAMENTOS_TB.ID_MEDICAMENTO%TYPE,
    P_DOSIS IN FIDE_INFANTES_MEDICAMENTOS_TB.DOSIS%TYPE,
    P_ID_ESTADO IN FIDE_INFANTES_MEDICAMENTOS_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_INFANTES_MEDICAMENTOS_DELETE_SP(
    P_CEDULA_INFANTE IN FIDE_INFANTES_MEDICAMENTOS_TB.CEDULA_INFANTE%TYPE,
    P_ID_MEDICAMENTO IN FIDE_INFANTES_MEDICAMENTOS_TB.ID_MEDICAMENTO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ACTIVIDAD_INSERT_SP(
    P_DESCRIPCION IN FIDE_ACTIVIDAD_TB.DESCRIPCION%TYPE,
    P_FECHA IN FIDE_ACTIVIDAD_TB.FECHA%TYPE,
    P_HORA IN FIDE_ACTIVIDAD_TB.HORA%TYPE,
    P_OBSERVACIONES IN FIDE_ACTIVIDAD_TB.OBSERVACIONES%TYPE,
    P_ID_ESTADO IN FIDE_ACTIVIDAD_TB.ID_ESTADO%TYPE,
    O_ID_ACTIVIDAD OUT FIDE_ACTIVIDAD_TB.ID_ACTIVIDAD%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ACTIVIDAD_UPDATE_SP(
    P_ID_ACTIVIDAD IN FIDE_ACTIVIDAD_TB.ID_ACTIVIDAD%TYPE,
    P_DESCRIPCION IN FIDE_ACTIVIDAD_TB.DESCRIPCION%TYPE,
    P_FECHA IN FIDE_ACTIVIDAD_TB.FECHA%TYPE,
    P_HORA IN FIDE_ACTIVIDAD_TB.HORA%TYPE,
    P_OBSERVACIONES IN FIDE_ACTIVIDAD_TB.OBSERVACIONES%TYPE,
    P_ID_ESTADO IN FIDE_ACTIVIDAD_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ACTIVIDAD_DELETE_SP(
    P_ID_ACTIVIDAD IN FIDE_ACTIVIDAD_TB.ID_ACTIVIDAD%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ACTIVIDAD_POR_GRUPO_INSERT_SP(
    P_ID_ACTIVIDAD IN FIDE_ACTIVIDAD_POR_GRUPO_TB.ID_ACTIVIDAD%TYPE,
    P_ID_GRUPO IN FIDE_ACTIVIDAD_POR_GRUPO_TB.ID_GRUPO%TYPE,
    P_ID_ESTADO IN FIDE_ACTIVIDAD_POR_GRUPO_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ACTIVIDAD_POR_GRUPO_UPDATE_SP(
    P_ID_ACTIVIDAD IN FIDE_ACTIVIDAD_POR_GRUPO_TB.ID_ACTIVIDAD%TYPE,
    P_ID_GRUPO IN FIDE_ACTIVIDAD_POR_GRUPO_TB.ID_GRUPO%TYPE,
    P_ID_ESTADO IN FIDE_ACTIVIDAD_POR_GRUPO_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ACTIVIDAD_POR_GRUPO_DELETE_SP(
    P_ID_ACTIVIDAD IN FIDE_ACTIVIDAD_POR_GRUPO_TB.ID_ACTIVIDAD%TYPE,
    P_ID_GRUPO IN FIDE_ACTIVIDAD_POR_GRUPO_TB.ID_GRUPO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CALIFICACION_INSERT_SP(
    P_CEDULA_INFANTE IN FIDE_CALIFICACION_TB.CEDULA_INFANTE%TYPE,
    P_ID_ACTIVIDAD IN FIDE_CALIFICACION_TB.ID_ACTIVIDAD%TYPE,
    P_CALIFICACION IN FIDE_CALIFICACION_TB.CALIFICACION%TYPE,
    P_OBSERVACIONES IN FIDE_CALIFICACION_TB.OBSERVACIONES%TYPE,
    P_ID_ESTADO IN FIDE_CALIFICACION_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CALIFICACION_UPDATE_SP(
    P_CEDULA_INFANTE IN FIDE_CALIFICACION_TB.CEDULA_INFANTE%TYPE,
    P_ID_ACTIVIDAD IN FIDE_CALIFICACION_TB.ID_ACTIVIDAD%TYPE,
    P_CALIFICACION IN FIDE_CALIFICACION_TB.CALIFICACION%TYPE,
    P_OBSERVACIONES IN FIDE_CALIFICACION_TB.OBSERVACIONES%TYPE,
    P_ID_ESTADO IN FIDE_CALIFICACION_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CALIFICACION_DELETE_SP(
    P_CEDULA_INFANTE IN FIDE_CALIFICACION_TB.CEDULA_INFANTE%TYPE,
    P_ID_ACTIVIDAD IN FIDE_CALIFICACION_TB.ID_ACTIVIDAD%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ENCABEZADO_FACTURA_INSERT_SP(
    P_CEDULA IN FIDE_ENCABEZADO_FACTURA_TB.CEDULA%TYPE,
    P_CEDULA_INFANTE IN FIDE_ENCABEZADO_FACTURA_TB.CEDULA_INFANTE%TYPE,
    P_FECHA_EMISION IN FIDE_ENCABEZADO_FACTURA_TB.FECHA_EMISION%TYPE,
    P_HORA_EMISION IN FIDE_ENCABEZADO_FACTURA_TB.HORA_EMISION%TYPE,
    P_SUBTOTAL IN FIDE_ENCABEZADO_FACTURA_TB.SUBTOTAL%TYPE,
    P_DESCUENTO IN FIDE_ENCABEZADO_FACTURA_TB.DESCUENTO%TYPE,
    P_IVA IN FIDE_ENCABEZADO_FACTURA_TB.IVA%TYPE,
    P_MONTO_TOTAL IN FIDE_ENCABEZADO_FACTURA_TB.MONTO_TOTAL%TYPE,
    P_ID_METODO_PAGO IN FIDE_ENCABEZADO_FACTURA_TB.ID_METODO_PAGO%TYPE,
    P_ID_ESTADO IN FIDE_ENCABEZADO_FACTURA_TB.ID_ESTADO%TYPE,
    O_ID_FACTURA OUT FIDE_ENCABEZADO_FACTURA_TB.ID_FACTURA%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ENCABEZADO_FACTURA_UPDATE_SP(
    P_ID_FACTURA IN FIDE_ENCABEZADO_FACTURA_TB.ID_FACTURA%TYPE,
    P_CEDULA IN FIDE_ENCABEZADO_FACTURA_TB.CEDULA%TYPE,
    P_CEDULA_INFANTE IN FIDE_ENCABEZADO_FACTURA_TB.CEDULA_INFANTE%TYPE,
    P_FECHA_EMISION IN FIDE_ENCABEZADO_FACTURA_TB.FECHA_EMISION%TYPE,
    P_HORA_EMISION IN FIDE_ENCABEZADO_FACTURA_TB.HORA_EMISION%TYPE,
    P_SUBTOTAL IN FIDE_ENCABEZADO_FACTURA_TB.SUBTOTAL%TYPE,
    P_DESCUENTO IN FIDE_ENCABEZADO_FACTURA_TB.DESCUENTO%TYPE,
    P_IVA IN FIDE_ENCABEZADO_FACTURA_TB.IVA%TYPE,
    P_MONTO_TOTAL IN FIDE_ENCABEZADO_FACTURA_TB.MONTO_TOTAL%TYPE,
    P_ID_METODO_PAGO IN FIDE_ENCABEZADO_FACTURA_TB.ID_METODO_PAGO%TYPE,
    P_ID_ESTADO IN FIDE_ENCABEZADO_FACTURA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_ENCABEZADO_FACTURA_DELETE_SP(
    P_ID_FACTURA IN FIDE_ENCABEZADO_FACTURA_TB.ID_FACTURA%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_DETALLE_FACTURA_INSERT_SP(
    P_ID_FACTURA IN FIDE_DETALLE_FACTURA_TB.ID_FACTURA%TYPE,
    P_ID_SERVICIO IN FIDE_DETALLE_FACTURA_TB.ID_SERVICIO%TYPE,
    P_MONTO_PAGADO IN FIDE_DETALLE_FACTURA_TB.MONTO_PAGADO%TYPE,
    P_ID_ESTADO IN FIDE_DETALLE_FACTURA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_DETALLE_FACTURA_UPDATE_SP(
    P_ID_FACTURA IN FIDE_DETALLE_FACTURA_TB.ID_FACTURA%TYPE,
    P_ID_SERVICIO IN FIDE_DETALLE_FACTURA_TB.ID_SERVICIO%TYPE,
    P_MONTO_PAGADO IN FIDE_DETALLE_FACTURA_TB.MONTO_PAGADO%TYPE,
    P_ID_ESTADO IN FIDE_DETALLE_FACTURA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_DETALLE_FACTURA_DELETE_SP(
    P_ID_FACTURA IN FIDE_DETALLE_FACTURA_TB.ID_FACTURA%TYPE,
    P_ID_SERVICIO IN FIDE_DETALLE_FACTURA_TB.ID_SERVICIO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_MATRICULA_INSERT_SP(
    P_CEDULA IN FIDE_MATRICULA_TB.CEDULA%TYPE,
    P_CEDULA_INFANTE IN FIDE_MATRICULA_TB.CEDULA_INFANTE%TYPE,
    P_ID_FACTURA IN FIDE_MATRICULA_TB.ID_FACTURA%TYPE,
    P_FECHA_MATRICULA IN FIDE_MATRICULA_TB.FECHA_MATRICULA%TYPE,
    P_ID_ESTADO IN FIDE_MATRICULA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_MATRICULA_UPDATE_SP(
    P_ID_MATRICULA IN FIDE_MATRICULA_TB.ID_MATRICULA%TYPE,
    P_CEDULA IN FIDE_MATRICULA_TB.CEDULA%TYPE,
    P_CEDULA_INFANTE IN FIDE_MATRICULA_TB.CEDULA_INFANTE%TYPE,
    P_ID_FACTURA IN FIDE_MATRICULA_TB.ID_FACTURA%TYPE,
    P_FECHA_MATRICULA IN FIDE_MATRICULA_TB.FECHA_MATRICULA%TYPE,
    P_ID_ESTADO IN FIDE_MATRICULA_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_MATRICULA_DELETE_SP(
    P_ID_MATRICULA IN FIDE_MATRICULA_TB.ID_MATRICULA%TYPE,
    P_CEDULA IN FIDE_MATRICULA_TB.CEDULA%TYPE,
    P_CEDULA_INFANTE IN FIDE_MATRICULA_TB.CEDULA_INFANTE%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_MENSUALIDAD_INSERT_SP(
    P_CEDULA IN FIDE_MENSUALIDAD_TB.CEDULA%TYPE,
    P_CEDULA_INFANTE IN FIDE_MENSUALIDAD_TB.CEDULA_INFANTE%TYPE,
    P_ID_FACTURA IN FIDE_MENSUALIDAD_TB.ID_FACTURA%TYPE,
    P_MES IN FIDE_MENSUALIDAD_TB.MES%TYPE,
    P_ID_ESTADO IN FIDE_MENSUALIDAD_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_MENSUALIDAD_UPDATE_SP(
    P_ID_MENSUALIDAD IN FIDE_MENSUALIDAD_TB.ID_MENSUALIDAD%TYPE,
    P_CEDULA IN FIDE_MENSUALIDAD_TB.CEDULA%TYPE,
    P_CEDULA_INFANTE IN FIDE_MENSUALIDAD_TB.CEDULA_INFANTE%TYPE,
    P_ID_FACTURA IN FIDE_MENSUALIDAD_TB.ID_FACTURA%TYPE,
    P_MES IN FIDE_MENSUALIDAD_TB.MES%TYPE,
    P_ID_ESTADO IN FIDE_MENSUALIDAD_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_MENSUALIDAD_DELETE_SP(
    P_ID_MENSUALIDAD IN FIDE_MENSUALIDAD_TB.ID_MENSUALIDAD%TYPE,
    P_CEDULA IN FIDE_MENSUALIDAD_TB.CEDULA%TYPE,
    P_CEDULA_INFANTE IN FIDE_MENSUALIDAD_TB.CEDULA_INFANTE%TYPE,
    P_ID_FACTURA IN FIDE_MENSUALIDAD_TB.ID_FACTURA%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PAGO_INSERT_SP(
    P_ID_FACTURA IN FIDE_PAGO_TB.ID_FACTURA%TYPE,
    P_MONTO_TOTAL IN FIDE_PAGO_TB.MONTO_TOTAL%TYPE,
    P_ID_ESTADO IN FIDE_PAGO_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PAGO_UPDATE_SP(
    P_ID_PAGO IN FIDE_PAGO_TB.ID_PAGO%TYPE,
    P_ID_FACTURA IN FIDE_PAGO_TB.ID_FACTURA%TYPE,
    P_MONTO_TOTAL IN FIDE_PAGO_TB.MONTO_TOTAL%TYPE,
    P_ID_ESTADO IN FIDE_PAGO_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_PAGO_DELETE_SP(
    P_ID_PAGO IN FIDE_PAGO_TB.ID_PAGO%TYPE,
    P_ID_FACTURA IN FIDE_PAGO_TB.ID_FACTURA%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_METODO_PAGO_INSERT_SP(
    P_ID_METODO_PAGO IN FIDE_METODO_PAGO_TB.ID_METODO_PAGO%TYPE,
    P_DESCRIPCION IN FIDE_METODO_PAGO_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO IN FIDE_METODO_PAGO_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_METODO_PAGO_UPDATE_SP(
    P_ID_METODO_PAGO IN FIDE_METODO_PAGO_TB.ID_METODO_PAGO%TYPE,
    P_DESCRIPCION IN FIDE_METODO_PAGO_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO IN FIDE_METODO_PAGO_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_METODO_PAGO_DELETE_SP(
    P_ID_METODO_PAGO IN FIDE_METODO_PAGO_TB.ID_METODO_PAGO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_SERVICIO_INSERT_SP(
    P_ID_SERVICIO IN FIDE_SERVICIO_TB.ID_SERVICIO%TYPE,
    P_DESCRIPCION IN FIDE_SERVICIO_TB.DESCRIPCION%TYPE,
    P_MONTO IN FIDE_SERVICIO_TB.MONTO%TYPE,
    P_ID_ESTADO IN FIDE_SERVICIO_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_SERVICIO_UPDATE_SP(
    P_ID_SERVICIO IN FIDE_SERVICIO_TB.ID_SERVICIO%TYPE,
    P_DESCRIPCION IN FIDE_SERVICIO_TB.DESCRIPCION%TYPE,
    P_MONTO IN FIDE_SERVICIO_TB.MONTO%TYPE,
    P_ID_ESTADO IN FIDE_SERVICIO_TB.ID_ESTADO%TYPE
);
----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_SERVICIO_DELETE_SP(
    P_ID_SERVICIO IN FIDE_SERVICIO_TB.ID_SERVICIO%TYPE
);
----------------------------------------------------------------------------------------------------------
------
------
------
------PROCEDIMIENTOS MAS COMPLEJOS
-- PROCEDIMIENTO COMPLETO PARA CREAR PERSONA
PROCEDURE FIDE_CREATE_PERSONA_FULL_SP(
    P_CEDULA IN FIDE_PERSONA_TB.CEDULA%TYPE,
    P_NOMBRE IN FIDE_PERSONA_TB.NOMBRE%TYPE,
    P_APELLIDO_PATERNO IN FIDE_PERSONA_TB.APELLIDO_PATERNO%TYPE,
    P_APELLIDO_MATERNO IN FIDE_PERSONA_TB.APELLIDO_MATERNO%TYPE,
    P_USERNAME IN FIDE_USUARIO_TB.USERNAME%TYPE,
    P_CONTRASENA IN FIDE_USUARIO_TB.CONTRASENA%TYPE,
    P_FECHA_NACIMIENTO IN FIDE_PERSONA_TB.FECHA_NACIMIENTO%TYPE,
    P_ID_ROL IN FIDE_PERSONA_TB.ID_ROL%TYPE,
    P_ID_PAIS IN FIDE_DIRECCION_TB.ID_PAIS%TYPE,
    P_ID_PROVINCIA IN FIDE_DIRECCION_TB.ID_PROVINCIA%TYPE,
    P_ID_CANTON IN FIDE_DIRECCION_TB.ID_CANTON%TYPE,
    P_ID_DISTRITO IN FIDE_DIRECCION_TB.ID_DISTRITO%TYPE,
    P_OTRAS_SENAS IN FIDE_DIRECCION_TB.OTRAS_SENAS%TYPE := NULL,
    P_ID_ESTADO IN FIDE_PERSONA_TB.ID_ESTADO%TYPE := 1
);
-----------------------------------------------------------------------------------------------------------
-- PROCEDIMIENTO COMPLETO PARA MODIFICAR PERSONA 
PROCEDURE FIDE_UPDATE_PERSONA_FULL_SP(
    P_CEDULA IN FIDE_PERSONA_TB.CEDULA%TYPE,
    P_NOMBRE IN FIDE_PERSONA_TB.NOMBRE%TYPE,
    P_APELLIDO_PATERNO IN FIDE_PERSONA_TB.APELLIDO_PATERNO%TYPE,
    P_APELLIDO_MATERNO IN FIDE_PERSONA_TB.APELLIDO_MATERNO%TYPE,
    P_USERNAME IN FIDE_USUARIO_TB.USERNAME%TYPE,
    P_CONTRASENA IN FIDE_USUARIO_TB.CONTRASENA%TYPE,
    P_FECHA_NACIMIENTO IN FIDE_PERSONA_TB.FECHA_NACIMIENTO%TYPE,
    P_ID_ROL IN FIDE_PERSONA_TB.ID_ROL%TYPE,
    P_ID_PAIS IN FIDE_DIRECCION_TB.ID_PAIS%TYPE,
    P_ID_PROVINCIA IN FIDE_DIRECCION_TB.ID_PROVINCIA%TYPE,
    P_ID_CANTON IN FIDE_DIRECCION_TB.ID_CANTON%TYPE,
    P_ID_DISTRITO IN FIDE_DIRECCION_TB.ID_DISTRITO%TYPE,
    P_OTRAS_SENAS IN FIDE_DIRECCION_TB.OTRAS_SENAS%TYPE := NULL,
    P_ID_ESTADO IN FIDE_PERSONA_TB.ID_ESTADO%TYPE := 1
);
-----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_FORMACION_ACADEMICA_TB_INSERT_AUTO_SP(
    P_CEDULA        IN FIDE_FORMACION_ACADEMICA_TB.CEDULA%TYPE,
    P_ID_INSTITUCION IN FIDE_FORMACION_ACADEMICA_TB.ID_INSTITUCION%TYPE,
    P_TITULO        IN FIDE_FORMACION_ACADEMICA_TB.TITULO%TYPE,
    P_FECHA_OBTENCION IN FIDE_FORMACION_ACADEMICA_TB.FECHA_OBTENCION%TYPE,
    P_ID_ESTADO     IN FIDE_FORMACION_ACADEMICA_TB.ID_ESTADO%TYPE
);
-----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_CAPACITACION_INSERT_AUTO_SP(
    P_CEDULA           IN FIDE_CAPACITACION_TB.CEDULA%TYPE,
    P_DESCRIPCION_TEMA IN FIDE_TEMA_TB.DESCRIPCION%TYPE,
    P_ID_PROVEEDOR     IN FIDE_CAPACITACION_TB.ID_PROVEEDOR%TYPE,
    P_ANIO             IN FIDE_CAPACITACION_TB.ANIO%TYPE,
    P_HORAS            IN FIDE_CAPACITACION_TB.HORAS%TYPE
);
-----------------------------------------------------------------------------------------------------------
PROCEDURE FIDE_EXPERIENCIA_LABORAL_AUTO_SP(
    P_CEDULA       IN FIDE_EXPERIENCIA_LABORAL_TB.CEDULA%TYPE,
    P_EMPRESA_DESC IN FIDE_EMPRESA_TB.DESCRIPCION%TYPE,
    P_ID_CARGO     IN FIDE_EXPERIENCIA_LABORAL_TB.ID_CARGO%TYPE,
    P_FECHA_INICIO IN FIDE_EXPERIENCIA_LABORAL_TB.FECHA_INICIO%TYPE,
    P_FECHA_FINAL  IN FIDE_EXPERIENCIA_LABORAL_TB.FECHA_FINAL%TYPE,
    P_ID_ESTADO    IN FIDE_EXPERIENCIA_LABORAL_TB.ID_ESTADO%TYPE
);
-----------------------------------------------------------------------------------------------------------









END FIDE_PROYECTO_LBD_PCK;

/
