--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_ESTADO_SEQ
CREATE OR REPLACE TRIGGER FIDE_ESTADO_SEQ_TRG
BEFORE INSERT ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := FIDE_ESTADO_SEQ.NEXTVAL;
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_PAIS_SEQ
CREATE OR REPLACE TRIGGER FIDE_PAIS_SEQ_TRG
BEFORE INSERT ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := FIDE_PAIS_SEQ.NEXTVAL;
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_PROVINCIA_SEQ
CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_SEQ_TRG
BEFORE INSERT ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_PROVINCIA := FIDE_PROVINCIA_SEQ.NEXTVAL;
    :NEW.ID_ESTADO := 1;
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_CANTON_SEQ
CREATE OR REPLACE TRIGGER FIDE_CANTON_SEQ_TRG
BEFORE INSERT ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_CANTON := FIDE_CANTON_SEQ.NEXTVAL;
    :NEW.ID_ESTADO := 1;
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_DISTRITO_SEQ
CREATE OR REPLACE TRIGGER FIDE_DISTRITO_SEQ_TRG
BEFORE INSERT ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_DISTRITO := FIDE_DISTRITO_SEQ.NEXTVAL;
    :NEW.ID_ESTADO := 1;
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_ROL_SEQ
CREATE OR REPLACE TRIGGER FIDE_ROL_SEQ_TRG
BEFORE INSERT ON FIDE_ROL_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ROL := FIDE_ROL_SEQ.NEXTVAL;
    :NEW.ID_ESTADO := 1;
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_CATEGORIA_SEQ
CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_SEQ_TRG
BEFORE INSERT ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_CATEGORIA := FIDE_CATEGORIA_SEQ.NEXTVAL;
    :NEW.ID_ESTADO := 1;
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_INSTITUCION_SEQ
CREATE OR REPLACE TRIGGER FIDE_INSTITUCION_SEQ_TRG
BEFORE INSERT ON FIDE_INSTITUCION_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_INSTITUCION := FIDE_INSTITUCION_SEQ.NEXTVAL;
    :NEW.ID_ESTADO := 1;
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_FORMACION_ACADEMICA_SEQ
CREATE OR REPLACE TRIGGER FIDE_FORMACION_ACADEMICA_SEQ_TRG
BEFORE INSERT ON FIDE_FORMACION_ACADEMICA_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_FORMACION := FIDE_FORMACION_ACADEMICA_SEQ.NEXTVAL;
    :NEW.ID_ESTADO := 1;
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_TEMA_SEQ
CREATE OR REPLACE TRIGGER FIDE_TEMA_SEQ_TRG
BEFORE INSERT ON FIDE_TEMA_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_TEMA := FIDE_TEMA_SEQ.NEXTVAL;
    :NEW.ID_ESTADO := 1;
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_PROVEEDOR_SEQ
CREATE OR REPLACE TRIGGER FIDE_PROVEEDOR_SEQ_TRG
BEFORE INSERT ON FIDE_PROVEEDOR_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_PROVEEDOR := FIDE_PROVEEDOR_SEQ.NEXTVAL;
    :NEW.ID_ESTADO := 1;
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_EMPRESA_SEQ
CREATE OR REPLACE TRIGGER FIDE_EMPRESA_SEQ_TRG
BEFORE INSERT ON FIDE_EMPRESA_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_EMPRESA := FIDE_EMPRESA_SEQ.NEXTVAL;
    :NEW.ID_ESTADO := 1;
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_CARGO_SEQ
CREATE OR REPLACE TRIGGER FIDE_CARGO_SEQ_TRG
BEFORE INSERT ON FIDE_CARGO_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_CARGO := FIDE_CARGO_SEQ.NEXTVAL;
    :NEW.ID_ESTADO := 1;
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_TIPO_EVALUACION_SEQ
CREATE OR REPLACE TRIGGER FIDE_TIPO_EVALUACION_SEQ_TRG
BEFORE INSERT ON FIDE_TIPO_EVALUACION_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_TIPO_EVALUACION := FIDE_TIPO_EVALUACION_SEQ.NEXTVAL;
    :NEW.ID_ESTADO := 1;
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_ALERGIA_SEQ
CREATE OR REPLACE TRIGGER FIDE_ALERGIA_SEQ_TRG
BEFORE INSERT ON FIDE_ALERGIA_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ALERGIA := FIDE_ALERGIA_SEQ.NEXTVAL;
    :NEW.ID_ESTADO := 1;
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_VACUNA_SEQ
CREATE OR REPLACE TRIGGER FIDE_VACUNA_SEQ_TRG
BEFORE INSERT ON FIDE_VACUNA_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_VACUNA := FIDE_VACUNA_SEQ.NEXTVAL;
    :NEW.ID_ESTADO := 1;
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_MEDICAMENTO_SEQ
CREATE OR REPLACE TRIGGER FIDE_MEDICAMENTO_SEQ_TRG
BEFORE INSERT ON FIDE_MEDICAMENTO_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_MEDICAMENTO := FIDE_MEDICAMENTO_SEQ.NEXTVAL;
    :NEW.ID_ESTADO := 1;
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_GRUPO_SEQ
CREATE OR REPLACE TRIGGER FIDE_GRUPO_SEQ_TRG
BEFORE INSERT ON FIDE_GRUPO_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_GRUPO := FIDE_GRUPO_SEQ.NEXTVAL;
    :NEW.ID_ESTADO := 1;
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_ACTIVIDAD_SEQ
CREATE OR REPLACE TRIGGER FIDE_ACTIVIDAD_SEQ_TRG
BEFORE INSERT ON FIDE_ACTIVIDAD_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ACTIVIDAD := FIDE_ACTIVIDAD_SEQ.NEXTVAL;
END;
/
--AUTOR: JOY CHAVEZ
--FECHA: 8/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_MATRICULA_SEQ
CREATE OR REPLACE TRIGGER FIDE_MATRICULA_SEQ_TRG
BEFORE INSERT ON FIDE_MATRICULA_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_MATRICULA := FIDE_MATRICULA_SEQ.NEXTVAL;
END;
/
--AUTOR: JOY CHAVEZ
--FECHA: 8/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_MENSUALIDAD_SEQ
CREATE OR REPLACE TRIGGER FIDE_MENSUALIDAD_SEQ_TRG
BEFORE INSERT ON FIDE_MENSUALIDAD_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_MENSUALIDAD := FIDE_MENSUALIDAD_SEQ.NEXTVAL;
END;
/
--AUTOR: JOY CHAVEZ
--FECHA: 8/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_PAGO_SEQ
CREATE OR REPLACE TRIGGER FIDE_PAGO_SEQ_TRG
BEFORE INSERT ON FIDE_PAGO_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_PAGO := FIDE_PAGO_SEQ.NEXTVAL;
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_ACTIVIDAD_SEQ
CREATE OR REPLACE TRIGGER FIDE_METODO_PAGO_SEQ_TRG
BEFORE INSERT ON FIDE_METODO_PAGO_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_METODO_PAGO := FIDE_METODO_PAGO_SEQ.NEXTVAL;
    :NEW.ID_ESTADO := 1;
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_ACTIVIDAD_SEQ
CREATE OR REPLACE TRIGGER FIDE_SERVICIO_SEQ_TRG
BEFORE INSERT ON FIDE_SERVICIO_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_SERVICIO := FIDE_SERVICIO_SEQ.NEXTVAL;
    :NEW.ID_ESTADO := 1;
END;
/
--AUTOR: JOY CHAVEZ
--FECHA: 8/12/2025
--CREACION DE FUNCION PARA SECUENCIA NUMERICA COMPUESTA
CREATE OR REPLACE FUNCTION FIDE_SECUENCIA_NUMERICA_FN
RETURN NUMBER AS
V_FECHA VARCHAR2(10);
V_SEQUENCIA NUMBER;
BEGIN
V_FECHA := TO_CHAR(SYSDATE, 'YYYYMMDD');
V_SEQUENCIA := TO_NUMBER(V_FECHA || LPAD(FIDE_FACTURA_SEQ.NEXTVAL, 10,0));
RETURN V_SEQUENCIA;
END FIDE_SECUENCIA_NUMERICA_FN;
/
--AUTOR: JOY CHAVEZ
--FECHA: 9/12/2025
--CREACION DE TRIGGER PARA SECUENCIA FIDE_FACTURA_SEQ
CREATE OR REPLACE TRIGGER FIDE_FACTURA_SEQ_TRG
BEFORE INSERT ON FIDE_ENCABEZADO_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_FACTURA := FIDE_SECUENCIA_NUMERICA_FN;
END;


