--CONFIGURACION INICIAL
--AUTOR: JONATHAN PAEZ PADILLA
--FECHA: 1/11/2025
--CREACION DEL USUARIO
CREATE USER PROYECTO_LBD IDENTIFIED BY 123;
/
--AUTOR: JONATHAN PAEZ PADILLA
--FECHA: 1/11/2025
--INICIAR SESSION
GRANT CREATE SESSION TO PROYECTO_LBD;
/
--AUTOR: JONATHAN PAEZ PADILLA
--FECHA: 1/11/2025
--PARA CREAR OBJETOS A NIVEL DE BASE DE DATOS
GRANT RESOURCE TO PROYECTO_LBD;
/
--AUTOR: JONATHAN PAEZ PADILLA
--FECHA: 1/11/2025
--CREAR UN TABLESPACE
CREATE TABLESPACE FIDE_PROYECTO_LBD_TBS
DATAFILE 'C:\ORACLE\ORADATA\XE\FIDE_PROYECTO_LBD_TBS.DBF' SIZE 100M;
/
--AUTOR: JONATHAN PAEZ PADILLA
--FECHA: 1/11/2025
--CREAR UN TABLESPACE TEMPORAL
CREATE TEMPORARY TABLESPACE FIDE_PROYECTO_LBD_TEMP_TBS
TEMPFILE 'C:\ORACLE\ORADATA\XE\FIDE_PROYECTO_LBD_TEMP_TBS.DBF' SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE 1G;
/
--AUTOR: JONATHAN PAEZ PADILLA
--FECHA: 1/11/2025
--ASIGNAMOS EL  TABLESPACE AL USUARIO PROYECTO_LBD
ALTER USER PROYECTO_LBD
TEMPORARY TABLESPACE FIDE_PROYECTO_LBD_TEMP_TBS;
/
--AUTOR: JONATHAN PAEZ PADILLA
--FECHA: 1/11/2025
--CREAR UN TABLESPACE UNDO
CREATE UNDO TABLESPACE FIDE_PROYECTO_LBD_UNDO
DATAFILE 'C:\ORACLE\ORADATA\XE\FIDE_PROYECTO_LBD_UNDO.DBF' SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE 1G;
/
--AUTOR: JONATHAN PAEZ PADILLA
--FECHA: 1/11/2025
--ESTABLECER EL UNDO COMO DEFAULT
ALTER SYSTEM SET undo_tablespace = FIDE_PROYECTO_LBD_UNDO;
/

DROP TABLESPACE FIDE_PROYECTO_LBD_TEMP_TBS INCLUDING CONTENTS AND DATAFILES; --TEMPORAL
