--CREACION DE TABLAS
--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_ESTADO_TB
CREATE TABLE FIDE_ESTADO_TB(
    ID_ESTADO NUMBER
        CONSTRAINT FIDE_ESTADO_TB_ID_ESTADO_PK PRIMARY KEY,
    DESCRIPCION VARCHAR2(50)
)TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_PAIS_TB
CREATE TABLE FIDE_PAIS_TB (
    ID_PAIS NUMBER
        CONSTRAINT FIDE_PAIS_TB_ID_PAIS_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_PAIS_TB_ID_ESTADO_FK 
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_PROVINCIA_TB
CREATE TABLE FIDE_PROVINCIA_TB(
    ID_PROVINCIA NUMBER
        CONSTRAINT FIDE_PROVINCIA_TB_ID_PROVINCIA_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_PROVINCIA_TB_ID_ESTADO_FK 
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
)TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_CANTON_TB
CREATE TABLE FIDE_CANTON_TB(
    ID_CANTON NUMBER
        CONSTRAINT FIDE_CANTON_TB_ID_CANTON_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_CANTON_TB_ID_ESTADO_FK 
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_DISTRITO_TB
CREATE TABLE FIDE_DISTRITO_TB (
    ID_DISTRITO NUMBER
        CONSTRAINT FIDE_DISTRITO_TB_ID_DISTRITO_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    ID_ESTADO   NUMBER,
    CONSTRAINT FIDE_DISTRITO_TB_ID_ESTADO_FK 
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/


--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_ROL_TB
CREATE TABLE FIDE_ROL_TB(
    ID_ROL NUMBER
        CONSTRAINT FIDE_ROL_TB_ID_ROL_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_ROL_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/


--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACIÓN DE TABLA FIDE_PERSONA_TB
CREATE TABLE FIDE_PERSONA_TB(
    CEDULA NUMBER CONSTRAINT FIDE_PERSONA_TB_CEDULA_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    APELLIDO_PATERNO VARCHAR2(100),
    APELLIDO_MATERNO VARCHAR2(100),
    FECHA_NACIMIENTO DATE,
    ID_ROL NUMBER,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_PERSONA_TB_ID_ROL_FK FOREIGN KEY(ID_ROL) REFERENCES FIDE_ROL_TB(ID_ROL),
    CONSTRAINT FIDE_PERSONA_TB_ID_ESTADO_FK FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/


--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACIÓN DE TABLA FIDE_DIRECCION_TB (PK compuesta como en el diagrama)
CREATE TABLE FIDE_DIRECCION_TB(
    CEDULA NUMBER,
    ID_PAIS NUMBER,
    ID_PROVINCIA NUMBER,
    ID_CANTON NUMBER,
    ID_DISTRITO NUMBER,
    OTRAS_SENAS VARCHAR2(500),
    ID_ESTADO NUMBER,
    
    CONSTRAINT FIDE_DIRECCION_TB_CEDULA_ID_PAIS_ID_PROVINCIA_ID_CANTON_ID_DISTRITO_PK
    PRIMARY KEY (CEDULA, ID_PAIS, ID_PROVINCIA, ID_CANTON, ID_DISTRITO),
    
    CONSTRAINT FIDE_DIRECCION_TB_CEDULA_FK
        FOREIGN KEY(CEDULA) REFERENCES FIDE_PERSONA_TB(CEDULA),
        
    CONSTRAINT FIDE_DIRECCION_TB_ID_PAIS_FK
        FOREIGN KEY(ID_PAIS) REFERENCES FIDE_PAIS_TB(ID_PAIS),
        
    CONSTRAINT FIDE_DIRECCION_TB_ID_PROVINCIA_FK
        FOREIGN KEY(ID_PROVINCIA) REFERENCES FIDE_PROVINCIA_TB(ID_PROVINCIA),
        
    CONSTRAINT FIDE_DIRECCION_TB_ID_CANTON_FK
        FOREIGN KEY(ID_CANTON) REFERENCES FIDE_CANTON_TB(ID_CANTON),
        
    CONSTRAINT FIDE_DIRECCION_TB_ID_DISTRITO_FK
        FOREIGN KEY(ID_DISTRITO) REFERENCES FIDE_DISTRITO_TB(ID_DISTRITO),
        
    CONSTRAINT FIDE_DIRECCION_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
        
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/
--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_USUARIO_TB
CREATE TABLE FIDE_USUARIO_TB(
    CEDULA NUMBER CONSTRAINT FIDE_USUARIO_TB_CEDULA_PK PRIMARY KEY,
    USERNAME VARCHAR2(100),
    CONTRASENA VARCHAR2(200),
    ID_ESTADO NUMBER,
    
    CONSTRAINT FIDE_USUARIO_TB_CEDULA_FK
        FOREIGN KEY(CEDULA) REFERENCES FIDE_PERSONA_TB(CEDULA),
        
    CONSTRAINT FIDE_USUARIO_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
        
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/
--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_EMAIL_TB
CREATE TABLE FIDE_EMAIL_TB(
    CEDULA NUMBER,
    EMAIL VARCHAR2(200),
    ID_ESTADO NUMBER,
    
    CONSTRAINT FIDE_EMAIL_TB_CEDULA_EMAIL_PK 
        PRIMARY KEY(CEDULA, EMAIL),
    
    CONSTRAINT FIDE_EMAIL_TB_CEDULA_FK
        FOREIGN KEY(CEDULA) REFERENCES FIDE_PERSONA_TB(CEDULA),
        
    CONSTRAINT FIDE_EMAIL_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
)TABLESPACE FIDE_PROYECTO_LBD_TBS;
/
--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_TELEFONO_TB
CREATE TABLE FIDE_TELEFONO_TB(
    CEDULA NUMBER,
    NUM_TELEFONO VARCHAR2(50),
    ID_ESTADO NUMBER,
    
    CONSTRAINT FIDE_TELEFONO_TB_CEDULA_NUM_TELEFONO_PK 
        PRIMARY KEY(CEDULA, NUM_TELEFONO),
    
    CONSTRAINT FIDE_TELEFONO_TB_CEDULA_FK
        FOREIGN KEY(CEDULA) REFERENCES FIDE_PERSONA_TB(CEDULA),
        
    CONSTRAINT FIDE_TELEFONO_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
        
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_CATEGORIA_TB
CREATE TABLE FIDE_CATEGORIA_TB(
    ID_CATEGORIA NUMBER
        CONSTRAINT FIDE_CATEGORIA_TB_ID_CATEGORIA_PK PRIMARY KEY,
    DESCRIPCION VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_CATEGORIA_TB_ID_ESTADO_FK 
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_INSTITUCION_TB
CREATE TABLE FIDE_INSTITUCION_TB(
    ID_INSTITUCION NUMBER CONSTRAINT FIDE_INSTITUCION_TB_ID_INSTITUCION_PK PRIMARY KEY,
    NOMBRE VARCHAR2(200),
    ID_CATEGORIA NUMBER,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_INSTITUCION_TB_ID_CATEGORIA_FK 
        FOREIGN KEY(ID_CATEGORIA) REFERENCES FIDE_CATEGORIA_TB(ID_CATEGORIA),
    CONSTRAINT FIDE_INSTITUCION_TB_ID_ESTADO_FK 
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_FORMACION_ACADEMICA_TB
CREATE TABLE FIDE_FORMACION_ACADEMICA_TB(
    ID_FORMACION NUMBER,
    CEDULA NUMBER,
    ID_INSTITUCION NUMBER,
    TITULO VARCHAR2(200),
    FECHA_OBTENCION DATE,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_FORMACION_ACADEMICA_TB_ID_FORMACION_CEDULA_PK PRIMARY KEY(ID_FORMACION, CEDULA),
    CONSTRAINT FIDE_FORMACION_ACADEMICA_TB_CEDULA_FK 
        FOREIGN KEY(CEDULA) REFERENCES FIDE_PERSONA_TB(CEDULA),
    CONSTRAINT FIDE_FORMACION_ACADEMICA_TB_ID_INSTITUCION_FK 
        FOREIGN KEY(ID_INSTITUCION) REFERENCES FIDE_INSTITUCION_TB(ID_INSTITUCION),
    CONSTRAINT FIDE_FORMACION_ACADEMICA_TB_ID_ESTADO_FK 
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_TEMA_TB
CREATE TABLE FIDE_TEMA_TB(
    ID_TEMA NUMBER
        CONSTRAINT FIDE_TEMA_TB_ID_TEMA_PK PRIMARY KEY,
    DESCRIPCION VARCHAR2(200),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_TEMA_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_PROVEEDOR_TB
CREATE TABLE FIDE_PROVEEDOR_TB(
    ID_PROVEEDOR NUMBER
        CONSTRAINT FIDE_PROVEEDOR_TB_ID_PROVEEDOR_PK PRIMARY KEY,
    DESCRIPCION VARCHAR2(200),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_PROVEEDOR_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
)TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_CAPACITACION_TB
CREATE TABLE FIDE_CAPACITACION_TB(	
    CEDULA NUMBER, 
	ID_TEMA NUMBER, 
	ID_PROVEEDOR NUMBER, 
	ANIO NUMBER, 
	HORAS NUMBER, 
	ID_ESTADO NUMBER, 
    
    CONSTRAINT FIDE_CAPACITACION_TB_CEDULA_ID_TEMA_ID_PROVEEDOR_ANIO_PK
        PRIMARY KEY (CEDULA, ID_TEMA, ID_PROVEEDOR, ANIO),
    
    CONSTRAINT FIDE_CAPACITACION_TB_CEDULA_FK FOREIGN KEY (CEDULA)
        REFERENCES FIDE_PERSONA_TB (CEDULA),
      
    CONSTRAINT FIDE_CAPACITACION_TB_ID_TEMA_FK FOREIGN KEY (ID_TEMA)
        REFERENCES FIDE_TEMA_TB (ID_TEMA), 
        
    CONSTRAINT FIDE_CAPACITACION_TB_ID_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR)
        REFERENCES FIDE_PROVEEDOR_TB (ID_PROVEEDOR), 
        
    CONSTRAINT FIDE_CAPACITACION_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB (ID_ESTADO)
        
)TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_EMPRESA_TB
CREATE TABLE FIDE_EMPRESA_TB(
    ID_EMPRESA NUMBER
        CONSTRAINT FIDE_EMPRESA_TB_ID_EMPRESA_PK PRIMARY KEY,
    DESCRIPCION VARCHAR2(200),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_EMPRESA_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_CARGO_TB
CREATE TABLE FIDE_CARGO_TB(
    ID_CARGO NUMBER
        CONSTRAINT FIDE_CARGO_TB_ID_CARGO_PK PRIMARY KEY,
    DESCRIPCION VARCHAR2(200),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_CARGO_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_EXPERIENCIA_LABORAL_TB
CREATE TABLE FIDE_EXPERIENCIA_LABORAL_TB(
    CEDULA NUMBER,
    ID_EMPRESA NUMBER,
    ID_CARGO NUMBER,
    FECHA_INICIO DATE,
    FECHA_FINAL DATE,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_EXPERIENCIA_LABORAL_TB_CEDULA_ID_EMPRESA_ID_CARGO_PK
        PRIMARY KEY (CEDULA, ID_EMPRESA, ID_CARGO),
        
    CONSTRAINT FIDE_EXPERIENCIA_LABORAL_TB_CEDULA_FK
        FOREIGN KEY(CEDULA) REFERENCES FIDE_PERSONA_TB(CEDULA),
        
    CONSTRAINT FIDE_EXPERIENCIA_LABORAL_TB_ID_EMPRESA_FK
        FOREIGN KEY(ID_EMPRESA) REFERENCES FIDE_EMPRESA_TB(ID_EMPRESA),
        
    CONSTRAINT FIDE_EXPERIENCIA_LABORAL_TB_ID_CARGO_FK
        FOREIGN KEY(ID_CARGO) REFERENCES FIDE_CARGO_TB(ID_CARGO),
        
    CONSTRAINT FIDE_EXPERIENCIA_LABORAL_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
        
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_TIPO_EVALUACION_TB
CREATE TABLE FIDE_TIPO_EVALUACION_TB(
    ID_TIPO_EVALUACION NUMBER
        CONSTRAINT FIDE_TIPO_EVALUACION_TB_ID_TIPO_EVALUACION_PK PRIMARY KEY,
    DESCRIPCION VARCHAR2(200),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_TIPO_EVALUACION_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_EVALUACION_DOCENTE_TB
CREATE TABLE FIDE_EVALUACION_DOCENTE_TB(
    CEDULA NUMBER,
    ID_TIPO_EVALUACION NUMBER,
    ANIO NUMBER,
    CALIFICACION VARCHAR2(100),
    COMENTARIOS VARCHAR2(1000),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_EVALUACION_DOCENTE_TB_CEDULA_ID_TIPO_EVALUACION_ANIO_PK
        PRIMARY KEY (CEDULA, ID_TIPO_EVALUACION, ANIO),
    CONSTRAINT FIDE_EVALUACION_DOCENTE_TB_CEDULA_FK
        FOREIGN KEY(CEDULA) REFERENCES FIDE_PERSONA_TB(CEDULA),
    CONSTRAINT FIDE_EVALUACION_DOCENTE_TB_ID_TIPO_EVALUACION_FK
        FOREIGN KEY(ID_TIPO_EVALUACION) REFERENCES FIDE_TIPO_EVALUACION_TB(ID_TIPO_EVALUACION),
    CONSTRAINT FIDE_EVALUACION_DOCENTE_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_INFANTE_TB
CREATE TABLE FIDE_INFANTE_TB(
    CEDULA_INFANTE NUMBER
        CONSTRAINT FIDE_INFANTE_TB_CEDULA_INFANTE_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    APELLIDO_PATERNO VARCHAR2(100),
    APELLIDO_MATERNO VARCHAR2(100),
    FECHA_NACIMIENTO DATE,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_INFANTE_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_ALERGIA_TB
CREATE TABLE FIDE_ALERGIA_TB(
    ID_ALERGIA NUMBER
        CONSTRAINT FIDE_ALERGIA_TB_ID_ALERGIA_PK PRIMARY KEY,
    NOMBRE VARCHAR2(200),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_ALERGIA_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_VACUNA_TB
CREATE TABLE FIDE_VACUNA_TB(
    ID_VACUNA NUMBER
        CONSTRAINT FIDE_VACUNA_TB_ID_VACUNA_PK PRIMARY KEY,
    TIPO_VACUNA VARCHAR2(200),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_VACUNA_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_MEDICAMENTO_TB
CREATE TABLE FIDE_MEDICAMENTO_TB(
    ID_MEDICAMENTO NUMBER
        CONSTRAINT FIDE_MEDICAMENTO_TB_ID_MEDICAMENTO_PK PRIMARY KEY,
    NOMBRE VARCHAR2(200),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_MEDICAMENTO_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

--AUTOR: JONATHAN PAEZ
--FECHA: 1/11/2025
--CREACION DE TABLA FIDE_TUTORES_INFANTES_TB
CREATE TABLE FIDE_TUTORES_INFANTES_TB(
    CEDULA NUMBER,
    CEDULA_INFANTE NUMBER,
    ID_ESTADO NUMBER,
    
    CONSTRAINT FIDE_TUTORES_INFANTES_TB_CEDULA_CEDULA_INFANTE_PK
        PRIMARY KEY (CEDULA, CEDULA_INFANTE),
        
    CONSTRAINT FIDE_TUTORES_INFANTES_TB_CEDULA_FK
        FOREIGN KEY(CEDULA) REFERENCES FIDE_PERSONA_TB(CEDULA),
        
    CONSTRAINT FIDE_TUTORES_INFANTES_TB_CEDULA_INFANTE_FK
        FOREIGN KEY(CEDULA_INFANTE) REFERENCES FIDE_INFANTE_TB(CEDULA_INFANTE),
        
    CONSTRAINT FIDE_TUTORES_INFANTES_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

-- AUTOR: NICOLE QUIROS RAMIREZ
-- FECHA: 02/11/2025
-- TABLA: FIDE_ASISTENCIA_TB
CREATE TABLE FIDE_ASISTENCIA_TB (
    CEDULA_INFANTE NUMBER,
    FECHA DATE,
    HORA_ENTRADA VARCHAR2(10),
    HORA_SALIDA VARCHAR2(10),
    OBSERVACIONES VARCHAR2(255),
    ID_ESTADO NUMBER,
    
    CONSTRAINT FIDE_ASISTENCIA_TB_CEDULA_INFANTE_FECHA_PK 
        PRIMARY KEY (CEDULA_INFANTE, FECHA),
        
    CONSTRAINT FIDE_ASISTENCIA_TB_CEDULA_INFANTE_FK 
        FOREIGN KEY (CEDULA_INFANTE) REFERENCES FIDE_INFANTE_TB(CEDULA_INFANTE),
        
    CONSTRAINT FIDE_ASISTENCIA_TB_ID_ESTADO_FK 
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

-- AUTOR: NICOLE QUIROS RAMIREZ
-- FECHA: 02/11/2025
-- TABLA: FIDE_GRUPO_TB
CREATE TABLE FIDE_GRUPO_TB(
    ID_GRUPO NUMBER,
    CEDULA NUMBER,
    NOMBRE VARCHAR(100),
    ID_ESTADO NUMBER,
    
    CONSTRAINT FIDE_GRUPO_TB_ID_GRUPO_PK
        PRIMARY KEY (ID_GRUPO),
    
    CONSTRAINT FIDE_GRUPO_TB_CEDULA_FK 
        FOREIGN KEY(CEDULA) REFERENCES FIDE_PERSONA_TB(CEDULA),
        
    CONSTRAINT FIDE_GRUPO_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

-- AUTOR: NICOLE QUIROS RAMIREZ
-- FECHA: 02/11/2025
-- TABLA: FIDE_DETALLE_GRUPO_TB
CREATE TABLE FIDE_DETALLE_GRUPO_TB(
    ID_GRUPO NUMBER,
    CEDULA_INFANTE NUMBER,
    ID_ESTADO NUMBER,
    
    CONSTRAINT FIDE_DETALLE_GRUPO_TB_ID_GRUPO_CEDULA_INFANTE_PK
        PRIMARY KEY (ID_GRUPO, CEDULA_INFANTE),
        
    CONSTRAINT FIDE_DETALLE_GRUPO_TB_ID_GRUPO_FK
        FOREIGN KEY(ID_GRUPO) REFERENCES FIDE_GRUPO_TB(ID_GRUPO),
        
    CONSTRAINT FIDE_DETALLE_GRUPO_TB_CEDULA_INFANTE_FK
        FOREIGN KEY(CEDULA_INFANTE) REFERENCES FIDE_INFANTE_TB(CEDULA_INFANTE),
        
    CONSTRAINT FIDE_DETALLE_GRUPO_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

-- AUTOR: NICOLE QUIROS RAMIREZ
-- FECHA: 02/11/2025
-- TABLA: FIDE_INFANTES_ALERGIAS_TB
CREATE TABLE FIDE_INFANTES_ALERGIAS_TB(
    CEDULA_INFANTE NUMBER,
    ID_ALERGIA NUMBER,
    OBSERVACION VARCHAR2(255),
    SEVERIDAD VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_INFANTES_ALERGIAS_TB_PK
        PRIMARY KEY (CEDULA_INFANTE, ID_ALERGIA),
        
    CONSTRAINT FIDE_INFANTES_ALERGIAS_TB_CEDULA_INFANTE_FK
        FOREIGN KEY(CEDULA_INFANTE) REFERENCES FIDE_INFANTE_TB(CEDULA_INFANTE),
        
    CONSTRAINT FIDE_INFANTES_ALERGIAS_TB_ID_ALERGIA_FK
        FOREIGN KEY(ID_ALERGIA) REFERENCES FIDE_ALERGIA_TB(ID_ALERGIA),
        
    CONSTRAINT FIDE_INFANTES_ALERGIAS_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

-- AUTOR: NICOLE QUIROS RAMIREZ
-- FECHA: 02/11/2025
-- TABLA: FIDE_INFANTES_VACUNAS_TB
CREATE TABLE FIDE_INFANTES_VACUNAS_TB(
    CEDULA_INFANTE NUMBER,
    ID_VACUNA NUMBER,
    FECHA DATE,
    ID_ESTADO NUMBER,
    
    CONSTRAINT FIDE_INFANTES_VACUNAS_TB_PK
        PRIMARY KEY (CEDULA_INFANTE, ID_VACUNA),
        
    CONSTRAINT FIDE_INFANTES_VACUNAS_TB_CEDULA_INFANTE_FK
        FOREIGN KEY(CEDULA_INFANTE) REFERENCES FIDE_INFANTE_TB(CEDULA_INFANTE),
        
    CONSTRAINT FIDE_INFANTES_VACUNAS_TB_ID_VACUNA_FK
        FOREIGN KEY(ID_VACUNA) REFERENCES FIDE_VACUNA_TB(ID_VACUNA),
        
    CONSTRAINT FIDE_INFANTES_VACUNAS_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

-- AUTOR: NICOLE QUIROS RAMIREZ
-- FECHA: 02/11/2025
-- TABLA: FIDE_INFANTES_MEDICAMENTOS_TB
CREATE TABLE FIDE_INFANTES_MEDICAMENTOS_TB(
    CEDULA_INFANTE NUMBER,
    ID_MEDICAMENTO NUMBER,
    DOSIS VARCHAR2(100),
    ID_ESTADO NUMBER,
    
    CONSTRAINT FIDE_INFANTES_MEDICAMENTOS_TB_PK
        PRIMARY KEY (CEDULA_INFANTE, ID_MEDICAMENTO),
        
    CONSTRAINT FIDE_INFANTES_MEDICAMENTOS_TB_CEDULA_INFANTE_FK
        FOREIGN KEY(CEDULA_INFANTE) REFERENCES FIDE_INFANTE_TB(CEDULA_INFANTE),
        
    CONSTRAINT FIDE_INFANTES_MEDICAMENTOS_TB_ID_MEDICAMENTO_FK
        FOREIGN KEY(ID_MEDICAMENTO) REFERENCES FIDE_MEDICAMENTO_TB(ID_MEDICAMENTO),
        
    CONSTRAINT FIDE_INFANTES_MEDICAMENTOS_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

-- AUTOR: NICOLE QUIROS RAMIREZ
-- FECHA: 02/11/2025
-- TABLA: FIDE_ACTIVIDAD_TB
CREATE TABLE FIDE_ACTIVIDAD_TB (
    ID_ACTIVIDAD NUMBER,
    DESCRIPCION VARCHAR2(255),
    FECHA DATE,
    HORA VARCHAR2(10),
    OBSERVACIONES VARCHAR2(255),
    ID_ESTADO NUMBER,
    
    CONSTRAINT FIDE_ACTIVIDAD_TB_ID_ACTIVIDAD_PK 
        PRIMARY KEY (ID_ACTIVIDAD),
        
    CONSTRAINT FIDE_ACTIVIDAD_TB_ID_ESTADO_FK 
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

-- AUTOR: NICOLE QUIROS RAMIREZ
-- FECHA: 02/11/2025
-- TABLA: FIDE_ACTIVIDAD_POR_GRUPO_TB
CREATE TABLE FIDE_ACTIVIDAD_POR_GRUPO_TB (
    ID_ACTIVIDAD NUMBER,
    ID_GRUPO NUMBER,
    ID_ESTADO NUMBER,
    
    CONSTRAINT FIDE_ACTIVIDAD_POR_GRUPO_TB_ID_ACTIVIDAD_ID_GRUPO_PK 
        PRIMARY KEY (ID_ACTIVIDAD, ID_GRUPO),
        
    CONSTRAINT FIDE_ACTIVIDAD_POR_GRUPO_TB_ID_ACTIVIDAD_FK 
        FOREIGN KEY (ID_ACTIVIDAD) REFERENCES FIDE_ACTIVIDAD_TB(ID_ACTIVIDAD),
        
    CONSTRAINT FIDE_ACTIVIDAD_POR_GRUPO_TB_ID_GRUPO_FK 
        FOREIGN KEY (ID_GRUPO) REFERENCES FIDE_GRUPO_TB(ID_GRUPO),
        
    CONSTRAINT FIDE_ACTIVIDAD_POR_GRUPO_TB_ID_ESTADO_FK 
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

-- AUTOR: NICOLE QUIROS RAMIREZ
-- FECHA: 02/11/2025
-- TABLA: FIDE_CALIFICACION_TB
CREATE TABLE FIDE_CALIFICACION_TB(
    CEDULA_INFANTE NUMBER,
    ID_ACTIVIDAD NUMBER,
    CALIFICACION NUMBER(3),
    OBSERVACIONES VARCHAR2(255),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_CALIFICACION_TB_CEDULA_INFANTE_ID_ACTIVIDAD_PK
        PRIMARY KEY (CEDULA_INFANTE, ID_ACTIVIDAD),
        
    CONSTRAINT FIDE_CALIFICACION_TB_CEDULA_INFANTE_FK
        FOREIGN KEY(CEDULA_INFANTE) REFERENCES FIDE_INFANTE_TB(CEDULA_INFANTE),
        
    CONSTRAINT FIDE_CALIFICACION_TB_ACTIVIDAD_FK
        FOREIGN KEY(ID_ACTIVIDAD) REFERENCES FIDE_ACTIVIDAD_TB(ID_ACTIVIDAD),
        
    CONSTRAINT FIDE_CALIFICACION_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/
-- AUTOR: NICOLE QUIROS RAMIREZ
-- FECHA: 02/11/2025
-- TABLA: FIDE_METODO_PAGO_TB
CREATE TABLE FIDE_METODO_PAGO_TB ( 
    ID_METODO_PAGO NUMBER
        CONSTRAINT FIDE_METODO_PAGO_TB_ID_METODO_PAGO_PK PRIMARY KEY,
    DESCRIPCION VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_METODO_PAGO_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

-- AUTOR: NICOLE QUIROS RAMIREZ
-- FECHA: 02/11/2025
-- TABLA: FIDE_SERVICIO_TB
CREATE TABLE FIDE_SERVICIO_TB (
    ID_SERVICIO NUMBER
        CONSTRAINT FIDE_SERVICIO_TB_ID_SERVICIO_PK PRIMARY KEY,
    DESCRIPCION VARCHAR2(200),
    MONTO NUMBER(10,2),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_SERVICIO_TB_ID_ESTADO_FK
        FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/
-- AUTOR: NICOLE QUIROS RAMIREZ
-- FECHA: 02/11/2025
-- TABLA: FIDE_ENCABEZADO_FACTURA_TB
CREATE TABLE FIDE_ENCABEZADO_FACTURA_TB(
    ID_FACTURA NUMBER,
    CEDULA NUMBER,
    CEDULA_INFANTE NUMBER,
    FECHA_EMISION DATE,
    HORA_EMISION VARCHAR2(10),
    SUBTOTAL NUMBER(10,2),
    DESCUENTO NUMBER(10,2),
    IVA NUMBER(10,2), 
    MONTO_TOTAL NUMBER(10,2),
    ID_METODO_PAGO NUMBER,
    ID_ESTADO NUMBER,
    
    CONSTRAINT FIDE_ENCABEZADO_FACTURA_TB_PK
        PRIMARY KEY (ID_FACTURA),
        
    CONSTRAINT FIDE_ENCABEZADO_FACTURA_TB_CEDULA_FK
        FOREIGN KEY(CEDULA) REFERENCES FIDE_PERSONA_TB(CEDULA),
        
    CONSTRAINT FIDE_ENCABEZADO_FACTURA_TB_CEDULA_INFANTE_FK
        FOREIGN KEY(CEDULA_INFANTE) REFERENCES FIDE_INFANTE_TB(CEDULA_INFANTE),
        
    CONSTRAINT FIDE_ENCABEZADO_FACTURA_TB_ID_METODO_PAGO_FK
        FOREIGN KEY(ID_METODO_PAGO) REFERENCES FIDE_METODO_PAGO_TB(ID_METODO_PAGO),
        
    CONSTRAINT FIDE_ENCABEZADO_FACTURA_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

-- AUTOR: NICOLE QUIROS RAMIREZ
-- FECHA: 02/11/2025
-- TABLA: FIDE_DETALLE_FACTURA_TB
CREATE TABLE FIDE_DETALLE_FACTURA_TB(
    ID_FACTURA NUMBER,
    ID_SERVICIO NUMBER,
    MONTO_PAGADO NUMBER(10,2),
    ID_ESTADO NUMBER,
    
    CONSTRAINT FIDE_DETALLE_FACTURA_TB_ID_FACTURA_ID_SERVICIO_PK
        PRIMARY KEY (ID_FACTURA, ID_SERVICIO),
        
    CONSTRAINT FIDE_DETALLE_FACTURA_TB_ID_FACTURA_FK
        FOREIGN KEY(ID_FACTURA) REFERENCES FIDE_ENCABEZADO_FACTURA_TB(ID_FACTURA),
        
    CONSTRAINT FIDE_DETALLE_FACTURA_TB_ID_SERVICIO_FK
        FOREIGN KEY(ID_SERVICIO) REFERENCES FIDE_SERVICIO_TB(ID_SERVICIO),
        
    CONSTRAINT FIDE_DETALLE_FACTURA_TB_ID_ESTADO_FK
        FOREIGN KEY(ID_ESTADO) REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

-- AUTOR: NICOLE QUIROS RAMIREZ
-- FECHA: 02/11/2025
-- TABLA: FIDE_MATRICULA_TB
CREATE TABLE FIDE_MATRICULA_TB(
    ID_MATRICULA NUMBER,
    CEDULA NUMBER,
    CEDULA_INFANTE NUMBER,
    ID_FACTURA NUMBER,
    FECHA_MATRICULA DATE,
    ID_ESTADO NUMBER,
    
    CONSTRAINT FIDE_MATRICULA_TB_ID_MATRICULA_CEDULA_CEDULA_INFANTE_PK 
        PRIMARY KEY (ID_MATRICULA, CEDULA, CEDULA_INFANTE),
    
    CONSTRAINT FIDE_MATRICULA_TB_CEDULA_INFANTE_FK FOREIGN KEY (CEDULA_INFANTE)
        REFERENCES FIDE_INFANTE_TB(CEDULA_INFANTE),
        
    CONSTRAINT FIDE_MATRICULA_TB_CEDULA_FK FOREIGN KEY (CEDULA)
        REFERENCES FIDE_PERSONA_TB(CEDULA),
        
    CONSTRAINT FIDE_MATRICULA_TB_ID_FACTURA_FK FOREIGN KEY (ID_FACTURA)
        REFERENCES FIDE_ENCABEZADO_FACTURA_TB(ID_FACTURA),
        
    CONSTRAINT FIDE_MATRICULA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/

-- AUTOR: NICOLE QUIROS RAMIREZ
-- FECHA: 02/11/2025
-- TABLA: FIDE_MENSUALIDAD_TB
CREATE TABLE FIDE_MENSUALIDAD_TB(
    ID_MENSUALIDAD NUMBER,
    CEDULA NUMBER,
    CEDULA_INFANTE NUMBER,
    ID_FACTURA NUMBER,
    MES VARCHAR2(20),
    ID_ESTADO NUMBER,
    
    CONSTRAINT FIDE_MENSUALIDAD_TB_ID_MENSUALIDAD_CEDULA_CEDULA_INFANTE_ID_FACTURA_PK 
        PRIMARY KEY (ID_MENSUALIDAD, CEDULA, CEDULA_INFANTE, ID_FACTURA),
    
    CONSTRAINT FIDE_MENSUALIDAD_TB_CEDULA_FK FOREIGN KEY (CEDULA)
        REFERENCES FIDE_PERSONA_TB(CEDULA),
        
    CONSTRAINT FIDE_MENSUALIDAD_TB_CEDULA_INFANTE_FK FOREIGN KEY (CEDULA_INFANTE)
        REFERENCES FIDE_INFANTE_TB(CEDULA_INFANTE),
        
    CONSTRAINT FIDE_MENSUALIDAD_TB_ID_FACTURA_FK FOREIGN KEY (ID_FACTURA)
        REFERENCES FIDE_ENCABEZADO_FACTURA_TB(ID_FACTURA),
        
    CONSTRAINT FIDE_MENSUALIDAD_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/



-- AUTOR: NICOLE QUIROS RAMIREZ
-- FECHA: 02/11/2025
-- TABLA: FIDE_FIDE_PAGO_TB
CREATE TABLE FIDE_PAGO_TB(
    ID_PAGO NUMBER,
    ID_FACTURA NUMBER,
    MONTO_TOTAL NUMBER(10,2),
    ID_ESTADO NUMBER,
    
    CONSTRAINT FIDE_PAGO_TB_ID_PAGO_ID_FACTURA_PK 
        PRIMARY KEY (ID_PAGO, ID_FACTURA),
    
    CONSTRAINT FIDE_PAGO_TB_ID_FACTURA_FK FOREIGN KEY (ID_FACTURA)
        REFERENCES FIDE_ENCABEZADO_FACTURA_TB(ID_FACTURA),
        
    CONSTRAINT FIDE_PAGO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
        
) TABLESPACE FIDE_PROYECTO_LBD_TBS;
/
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- SELECTS A TODAS LAS TABLAS 

SELECT * FROM FIDE_ESTADO_TB;
SELECT * FROM FIDE_PAIS_TB;
SELECT * FROM FIDE_PROVINCIA_TB;
SELECT * FROM FIDE_CANTON_TB;
SELECT * FROM FIDE_DISTRITO_TB;
SELECT * FROM FIDE_ROL_TB;
SELECT * FROM FIDE_CATEGORIA_TB;
SELECT * FROM FIDE_METODO_PAGO_TB;
SELECT * FROM FIDE_SERVICIO_TB;
SELECT * FROM FIDE_INSTITUCION_TB;
SELECT * FROM FIDE_PERSONA_TB;
SELECT * FROM FIDE_FORMACION_ACADEMICA_TB;
SELECT * FROM FIDE_TEMA_TB;
SELECT * FROM FIDE_PROVEEDOR_TB;
SELECT * FROM FIDE_CAPACITACION_TB;
SELECT * FROM FIDE_DIRECCION_TB;
SELECT * FROM FIDE_EMAIL_TB;
SELECT * FROM FIDE_TELEFONO_TB;
SELECT * FROM FIDE_USUARIO_TB;
SELECT * FROM FIDE_EMPRESA_TB;
SELECT * FROM FIDE_CARGO_TB;
SELECT * FROM FIDE_EXPERIENCIA_LABORAL_TB;
SELECT * FROM FIDE_TIPO_EVALUACION_TB;
SELECT * FROM FIDE_EVALUACION_DOCENTE_TB;
SELECT * FROM FIDE_INFANTE_TB;
SELECT * FROM FIDE_TUTORES_INFANTES_TB;
SELECT * FROM FIDE_ALERGIA_TB;
SELECT * FROM FIDE_VACUNA_TB;
SELECT * FROM FIDE_MEDICAMENTO_TB;
SELECT * FROM FIDE_INFANTES_ALERGIAS_TB;
SELECT * FROM FIDE_INFANTES_VACUNAS_TB;
SELECT * FROM FIDE_INFANTES_MEDICAMENTOS_TB;
SELECT * FROM FIDE_GRUPO_TB;
SELECT * FROM FIDE_DETALLE_GRUPO_TB;
SELECT * FROM FIDE_ACTIVIDAD_TB;
SELECT * FROM FIDE_ACTIVIDAD_POR_GRUPO_TB;
SELECT * FROM FIDE_CALIFICACION_TB;
SELECT * FROM FIDE_ASISTENCIA_TB;
SELECT * FROM FIDE_ENCABEZADO_FACTURA_TB;
SELECT * FROM FIDE_DETALLE_FACTURA_TB;
SELECT * FROM FIDE_MATRICULA_TB;
SELECT * FROM FIDE_MENSUALIDAD_TB;
SELECT * FROM FIDE_PAGO_TB;
