--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_ESTADO_TB_INSERTAR_TRG
BEFORE INSERT ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_ESTADO_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_PAIS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_PAIS_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_TB_INSERT_TRG
BEFORE INSERT ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_CANTON_TB_INSERT_TRG
BEFORE INSERT ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_CANTON_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_DISTRITO_TB_INSERT_TRG
BEFORE INSERT ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_DISTRITO_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_ROL_TB_INSERT_TRG
BEFORE INSERT ON FIDE_ROL_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_ROL_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_ROL_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_TB_INSERT_TRG
BEFORE INSERT ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_METODO_PAGO_TB_INSERT_TRG
BEFORE INSERT ON FIDE_METODO_PAGO_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_METODO_PAGO := FIDE_METODO_PAGO_SEQ.NEXTVAL;
    :NEW.ID_ESTADO := 1;
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_METODO_PAGO_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_METODO_PAGO_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_SERVICIO_TB_INSERT_TRG
BEFORE INSERT ON FIDE_SERVICIO_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_SERVICIO_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_SERVICIO_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_INSTITUCION_TB_INSERT_TRG
BEFORE INSERT ON FIDE_INSTITUCION_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_INSTITUCION_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_INSTITUCION_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_PERSONA_TB_INSERT_TRG
BEFORE INSERT ON FIDE_PERSONA_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_PERSONA_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_PERSONA_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_FORMACION_ACADEMICA_TB_INSERT_TRG
BEFORE INSERT ON FIDE_FORMACION_ACADEMICA_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_FORMACION_ACADEMICA_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_FORMACION_ACADEMICA_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_TEMA_TB_INSERT_TRG
BEFORE INSERT ON FIDE_TEMA_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    :NEW.ID_TEMA := FIDE_TEMA_SEQ.NEXTVAL;
    :NEW.ID_ESTADO := 1;
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_TEMA_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_TEMA_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_PROVEEDOR_TB_INSERT_TRG
BEFORE INSERT ON FIDE_PROVEEDOR_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_PROVEEDOR_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_PROVEEDOR_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_CAPACITACION_TB_INSERT_TRG
BEFORE INSERT ON FIDE_CAPACITACION_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_CAPACITACION_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_CAPACITACION_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_DIRECCION_TB_INSERT_TRG
BEFORE INSERT ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_DIRECCION_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_EMAIL_TB_INSERT_TRG
BEFORE INSERT ON FIDE_EMAIL_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_EMAIL_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_EMAIL_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_TELEFONO_TB_INSERT_TRG
BEFORE INSERT ON FIDE_TELEFONO_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_TELEFONO_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_TELEFONO_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_USUARIO_TB_INSERT_TRG
BEFORE INSERT ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_USUARIO_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_EMPRESA_TB_INSERT_TRG
BEFORE INSERT ON FIDE_EMPRESA_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_EMPRESA_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_EMPRESA_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_CARGO_TB_INSERT_TRG
BEFORE INSERT ON FIDE_CARGO_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_CARGO_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_CARGO_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_EXPERIENCIA_LABORAL_TB_INSERT_TRG
BEFORE INSERT ON FIDE_EXPERIENCIA_LABORAL_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_EXPERIENCIA_LABORAL_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_EXPERIENCIA_LABORAL_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_TIPO_EVALUACION_TB_INSERT_TRG
BEFORE INSERT ON FIDE_TIPO_EVALUACION_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_TIPO_EVALUACION_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPO_EVALUACION_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_EVALUACION_DOCENTE_TB_INSERT_TRG
BEFORE INSERT ON FIDE_EVALUACION_DOCENTE_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_EVALUACION_DOCENTE_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_EVALUACION_DOCENTE_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_INFANTE_TB_INSERT_TRG
BEFORE INSERT ON FIDE_INFANTE_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_INFANTE_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_INFANTE_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_TUTORES_INFANTES_TB_INSERT_TRG
BEFORE INSERT ON FIDE_TUTORES_INFANTES_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_TUTORES_INFANTES_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_TUTORES_INFANTES_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_ALERGIA_TB_INSERT_TRG
BEFORE INSERT ON FIDE_ALERGIA_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_ALERGIA_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_ALERGIA_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_VACUNA_TB_INSERT_TRG
BEFORE INSERT ON FIDE_VACUNA_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_VACUNA_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_VACUNA_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_MEDICAMENTO_TB_INSERT_TRG
BEFORE INSERT ON FIDE_MEDICAMENTO_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_MEDICAMENTO_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_MEDICAMENTO_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_INFANTES_ALERGIAS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_INFANTES_ALERGIAS_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_INFANTES_ALERGIAS_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_INFANTES_ALERGIAS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_INFANTES_VACUNAS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_INFANTES_VACUNAS_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_INFANTES_VACUNAS_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_INFANTES_VACUNAS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_INFANTES_MEDICAMENTOS_TB_INSERT_TRG
BEFORE INSERT ON FIDE_INFANTES_MEDICAMENTOS_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_INFANTES_MEDICAMENTOS_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_INFANTES_MEDICAMENTOS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_GRUPO_TB_INSERT_TRG
BEFORE INSERT ON FIDE_GRUPO_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_GRUPO_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_GRUPO_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_DETALLE_GRUPO_TB_INSERT_TRG
BEFORE INSERT ON FIDE_DETALLE_GRUPO_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_DETALLE_GRUPO_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_DETALLE_GRUPO_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_ACTIVIDAD_TB_INSERT_TRG
BEFORE INSERT ON FIDE_ACTIVIDAD_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_ACTIVIDAD_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_ACTIVIDAD_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_ACTIVIDAD_POR_GRUPO_TB_INSERT_TRG
BEFORE INSERT ON FIDE_ACTIVIDAD_POR_GRUPO_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_ACTIVIDAD_POR_GRUPO_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_ACTIVIDAD_POR_GRUPO_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_CALIFICACION_TB_INSERT_TRG
BEFORE INSERT ON FIDE_CALIFICACION_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_CALIFICACION_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_CALIFICACION_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR INSERT
CREATE OR REPLACE TRIGGER FIDE_ASISTENCIA_TB_INSERT_TRG
BEFORE INSERT ON FIDE_ASISTENCIA_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_ASISTENCIA_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_ASISTENCIA_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
CREATE OR REPLACE TRIGGER FIDE_ENCABEZADO_FACTURA_TB_INSERT_TRG
BEFORE INSERT ON FIDE_ENCABEZADO_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_ENCABEZADO_FACTURA_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_ENCABEZADO_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
CREATE OR REPLACE TRIGGER FIDE_DETALLE_FACTURA_TB_INSERT_TRG
BEFORE INSERT ON FIDE_DETALLE_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_DETALLE_FACTURA_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_DETALLE_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
CREATE OR REPLACE TRIGGER FIDE_MATRICULA_TB_INSERT_TRG
BEFORE INSERT ON FIDE_MATRICULA_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_MATRICULA_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_MATRICULA_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
CREATE OR REPLACE TRIGGER FIDE_MENSUALIDAD_TB_INSERT_TRG
BEFORE INSERT ON FIDE_MENSUALIDAD_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_MENSUALIDAD_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_MENSUALIDAD_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/
CREATE OR REPLACE TRIGGER FIDE_PAGO_TB_INSERT_TRG
BEFORE INSERT ON FIDE_PAGO_TB
FOR EACH ROW
BEGIN
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE TRIGGER PARA AUDITAR UPDATE
CREATE OR REPLACE TRIGGER FIDE_PAGO_TB_UPDATE_TRG
BEFORE UPDATE ON FIDE_PAGO_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;