--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE SECUENCIA PARA FIDE_ESTADO_TB
CREATE SEQUENCE FIDE_ESTADO_SEQ START WITH 7 INCREMENT BY 1;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE SECUENCIA PARA FIDE_PAIS_TB
CREATE SEQUENCE FIDE_PAIS_SEQ START WITH 2 INCREMENT BY 1;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE SECUENCIA PARA FIDE_PROVINCIA_TB
CREATE SEQUENCE FIDE_PROVINCIA_SEQ START WITH 8 INCREMENT BY 1;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE SECUENCIA PARA FIDE_CANTON_TB
CREATE SEQUENCE FIDE_CANTON_SEQ START WITH 16 INCREMENT BY 1;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE SECUENCIA FIDE_DISTRITO_TB
CREATE SEQUENCE FIDE_DISTRITO_SEQ START WITH 31 INCREMENT BY 1;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE SECUENCIA PARA FIDE_ROL_TB
CREATE SEQUENCE FIDE_ROL_SEQ START WITH 4 INCREMENT BY 1;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE SECUENCIA PARA FIDE_CATEGORIA_TB
CREATE SEQUENCE FIDE_CATEGORIA_SEQ START WITH 4 INCREMENT BY 1;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE SECUENCIA PARA FIDE_INSTITUCION_TB
CREATE SEQUENCE FIDE_INSTITUCION_SEQ START WITH 51 INCREMENT BY 1;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE SECUENCIA PARA FIDE_FORMACION_ACADEMICA_TB
CREATE SEQUENCE FIDE_FORMACION_ACADEMICA_SEQ START WITH 50 INCREMENT BY 1;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE SECUENCIA PARA FIDE_TEMA_TB
CREATE SEQUENCE FIDE_TEMA_SEQ START WITH 50 INCREMENT BY 1;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE SECUENCIA PARA FIDE_PROVEEDOR_TB
CREATE SEQUENCE FIDE_PROVEEDOR_SEQ START WITH 50 INCREMENT BY 1;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE SECUENCIA PARA FIDE_EMPRESA_TB
CREATE SEQUENCE FIDE_EMPRESA_SEQ START WITH 50 INCREMENT BY 1;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE SECUENCIA PARA FIDE_CARGO_TB
CREATE SEQUENCE FIDE_CARGO_SEQ START WITH 50 INCREMENT BY 1;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE SECUENCIA PARA FIDE_TIPO_EVALUACION_TB
CREATE SEQUENCE FIDE_TIPO_EVALUACION_SEQ START WITH 50 INCREMENT BY 1;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE SECUENCIA PARA FIDE_ALERGIA_TB
CREATE SEQUENCE FIDE_ALERGIA_SEQ START WITH 51 INCREMENT BY 1;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE SECUENCIA PARA FIDE_VACUNA_TB
CREATE SEQUENCE FIDE_VACUNA_SEQ START WITH 51 INCREMENT BY 1;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE SECUENCIA PARA FIDE_MEDICAMENTO_TB
CREATE SEQUENCE FIDE_MEDICAMENTO_SEQ START WITH 51 INCREMENT BY 1;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE SECUENCIA PARA FIDE_GRUPO_TB
CREATE SEQUENCE FIDE_GRUPO_SEQ START WITH 16 INCREMENT BY 1;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE SECUENCIA PARA FIDE_ACTIVIDAD_TB
CREATE SEQUENCE FIDE_ACTIVIDAD_SEQ START WITH 46 INCREMENT BY 1;
/
--AUTOR: JOY CHAVEZ
--FECHA: 8/12/2025
--CREACION DE SECUENCIA PARA FIDE_MATRICULA_TB
CREATE SEQUENCE FIDE_MATRICULA_SEQ START WITH 76 INCREMENT BY 1;
/
--AUTOR: JOY CHAVEZ
--FECHA: 8/12/2025
--CREACION DE SECUENCIA PARA FIDE_MENSUALIDAD_TB
CREATE SEQUENCE FIDE_MENSUALIDAD_SEQ START WITH 76 INCREMENT BY 1;
/
--AUTOR: JOY CHAVEZ
--FECHA: 8/12/2025
--CREACION DE SECUENCIA PARA FIDE_PAGO_TB
CREATE SEQUENCE FIDE_PAGO_SEQ START WITH 151 INCREMENT BY 1;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE SECUENCIA PARA FIDE_METODO_PAGO_TB
CREATE SEQUENCE FIDE_METODO_PAGO_SEQ START WITH 4 INCREMENT BY 1;
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--CREACION DE SECUENCIA PARA FIDE_SERVICIO_TB
CREATE SEQUENCE FIDE_SERVICIO_SEQ START WITH 3 INCREMENT BY 1;
--AUTOR: JOY CHAVEZ
--FECHA: 8/12/2025
--CREACION DE SECUENCIA PARA FIDE_ENCABEZADO_FACTURA_TB
CREATE SEQUENCE FIDE_FACTURA_SEQ START WITH 151 INCREMENT BY 1;