/*
AUTOR: JONATHAN PAEZ
FECHA: 14/11/25
VISTA PARA EL MODULO DE GESTION USUARIO
*/
CREATE OR REPLACE VIEW FIDE_PERSONA_USUARIO_ROL_V AS
SELECT
    P.CEDULA,
    P.NOMBRE,
    P.APELLIDO_PATERNO,
    P.APELLIDO_MATERNO,
    P.FECHA_NACIMIENTO,
    U.USERNAME,
    U.CONTRASENA,
    R.NOMBRE AS ROL,
    P.ID_ROL,
    D.ID_PAIS,
    D.ID_PROVINCIA,
    D.ID_CANTON,
    D.ID_DISTRITO,
    D.OTRAS_SENAS,
    P.ID_ESTADO
FROM FIDE_PERSONA_TB P
JOIN FIDE_USUARIO_TB U
    ON P.CEDULA = U.CEDULA
JOIN FIDE_ROL_TB R
    ON P.ID_ROL = R.ID_ROL
LEFT JOIN FIDE_DIRECCION_TB D
    ON D.CEDULA = P.CEDULA;
/
/*
VISTA PARA PLANIFICACION DE ACTIVIDADES
AUTOR: NICOLE QUIROS RAMIREZ
FECHA: 17/11/25
*/
CREATE OR REPLACE VIEW FIDE_ACTIVIDAD_GRUPO_V AS
SELECT
    A.ID_ACTIVIDAD,
    A.DESCRIPCION,
    A.FECHA,
    A.HORA,
    A.OBSERVACIONES,
    A.ID_ESTADO,
    E.DESCRIPCION AS ESTADO_ACTIVIDAD,
    G.ID_GRUPO,
    G.NOMBRE AS NOMBRE_GRUPO,
    G.CEDULA AS CEDULA_ENCARGADO,
    GE.DESCRIPCION AS ESTADO_GRUPO
FROM FIDE_ACTIVIDAD_TB A
LEFT JOIN FIDE_ACTIVIDAD_POR_GRUPO_TB AG
    ON A.ID_ACTIVIDAD = AG.ID_ACTIVIDAD
LEFT JOIN FIDE_GRUPO_TB G
    ON AG.ID_GRUPO = G.ID_GRUPO
LEFT JOIN FIDE_ESTADO_TB E
    ON A.ID_ESTADO = E.ID_ESTADO
LEFT JOIN FIDE_ESTADO_TB GE
    ON G.ID_ESTADO = GE.ID_ESTADO;
/
/*
VISTA PARA REGISTRO DE ASISTENCIA--
AUTOR: NICOLE QUIROS RAMIREZ
FECHA: 17/11/25
*/
CREATE OR REPLACE VIEW FIDE_REGISTRO_ASISTENCIA_V AS
SELECT
    A.CEDULA_INFANTE,
    I.NOMBRE AS NOMBRE_INFANTE,
    I.APELLIDO_PATERNO,
    I.APELLIDO_MATERNO,
    I.FECHA_NACIMIENTO,
    A.FECHA AS FECHA_ASISTENCIA,
    A.HORA_ENTRADA,
    A.HORA_SALIDA,
    A.OBSERVACIONES,
    E.DESCRIPCION AS ESTADO_ASISTENCIA
FROM FIDE_ASISTENCIA_TB A
LEFT JOIN FIDE_INFANTE_TB I
    ON A.CEDULA_INFANTE = I.CEDULA_INFANTE
LEFT JOIN FIDE_ESTADO_TB E
    ON A.ID_ESTADO = E.ID_ESTADO
ORDER BY A.FECHA DESC, I.NOMBRE;
/
/*
AUTOR: YEIK PACHECO
FECHA: 18/11/25
VISTA PARA EL MODULO DE GESTION INFANTES
*/
CREATE OR REPLACE VIEW FIDE_GESTION_INFANTES_V AS
SELECT 
    I.CEDULA_INFANTE,
    I.NOMBRE,
    I.APELLIDO_PATERNO,
    I.APELLIDO_MATERNO,
    I.FECHA_NACIMIENTO,
    I.ID_ESTADO AS ESTADO,
    T.CEDULA AS CEDULA_PADRE,
    G.NOMBRE AS NOMBRE_GRUPO,
    -- Alergias
    (
        SELECT LISTAGG(A.NOMBRE, ', ') WITHIN GROUP (ORDER BY A.NOMBRE)
        FROM FIDE_INFANTES_ALERGIAS_TB IA
        JOIN FIDE_ALERGIA_TB A 
            ON IA.ID_ALERGIA = A.ID_ALERGIA
        WHERE IA.CEDULA_INFANTE = I.CEDULA_INFANTE
    ) AS ALERGIAS,
    -- Medicamentos
    (
        SELECT LISTAGG(M.NOMBRE, ', ') WITHIN GROUP (ORDER BY M.NOMBRE)
        FROM FIDE_INFANTES_MEDICAMENTOS_TB IM
        JOIN FIDE_MEDICAMENTO_TB M 
            ON IM.ID_MEDICAMENTO = M.ID_MEDICAMENTO
        WHERE IM.CEDULA_INFANTE = I.CEDULA_INFANTE
    ) AS MEDICAMENTOS,
    -- Vacunas
    (
        SELECT LISTAGG(V.TIPO_VACUNA, ', ') WITHIN GROUP (ORDER BY V.TIPO_VACUNA)
        FROM FIDE_INFANTES_VACUNAS_TB IV
        JOIN FIDE_VACUNA_TB V 
            ON IV.ID_VACUNA = V.ID_VACUNA
        WHERE IV.CEDULA_INFANTE = I.CEDULA_INFANTE
    ) AS VACUNAS

FROM FIDE_INFANTE_TB I
LEFT JOIN FIDE_DETALLE_GRUPO_TB DG
    ON DG.CEDULA_INFANTE = I.CEDULA_INFANTE
LEFT JOIN FIDE_GRUPO_TB G
    ON G.ID_GRUPO = DG.ID_GRUPO
LEFT JOIN FIDE_TUTORES_INFANTES_TB T
    ON T.CEDULA_INFANTE = I.CEDULA_INFANTE;
/
/*
AUTOR: JONATHAN PAEZ
FECHA: 14/11/25
VISTA PARA EL MODULO DE GESTION DOCENTE (FORMACION ACADEMICA)
*/
CREATE OR REPLACE VIEW FIDE_FORMACION_ACADEMICA_V AS
SELECT
    F.ID_FORMACION,
    P.CEDULA,
    F.TITULO,
    I.NOMBRE AS INSTITUCION,
    C.DESCRIPCION AS CATEGORIA,
    F.FECHA_OBTENCION,
    F.ID_ESTADO,
    E.DESCRIPCION AS ESTADO
FROM FIDE_FORMACION_ACADEMICA_TB F
JOIN FIDE_PERSONA_TB P
    ON F.CEDULA = P.CEDULA
JOIN FIDE_INSTITUCION_TB I
    ON F.ID_INSTITUCION = I.ID_INSTITUCION
JOIN FIDE_CATEGORIA_TB C
    ON I.ID_CATEGORIA = C.ID_CATEGORIA
JOIN FIDE_ESTADO_TB E
    ON F.ID_ESTADO=E.ID_ESTADO;
/
/*
AUTOR: JONATHAN PAEZ
FECHA: 14/11/25
VISTA PARA EL MODULO DE GESTION DOCENTE (CAPACITACION)
*/
CREATE OR REPLACE VIEW FIDE_CAPACITACION_V AS
SELECT
    P.CEDULA,
    C.ID_TEMA,
    T.DESCRIPCION AS TEMA,
    C.ID_PROVEEDOR,
    PR.DESCRIPCION AS PROVEEDOR,
    C.ANIO,
    C.HORAS,
    C.ID_ESTADO
FROM FIDE_CAPACITACION_TB C
JOIN FIDE_PERSONA_TB P
    ON P.CEDULA=C.CEDULA
JOIN FIDE_TEMA_TB T
    ON C.ID_TEMA=T.ID_TEMA
JOIN FIDE_PROVEEDOR_TB PR
    ON C.ID_PROVEEDOR=PR.ID_PROVEEDOR;
/
/*
AUTOR: JONATHAN PAEZ
FECHA: 14/11/25
VISTA PARA EL MODULO DE GESTION DOCENTE (EXPERIENCIA LABORAL)
*/
CREATE OR REPLACE VIEW FIDE_EXPERIENCIA_LABORAL_V AS
SELECT
    P.CEDULA,
    E.ID_EMPRESA,
    EM.DESCRIPCION AS EMPRESA,
    E.ID_CARGO,
    C.DESCRIPCION AS CARGO,
    E.FECHA_INICIO,
    E.FECHA_FINAL,
    E.ID_ESTADO
FROM FIDE_EXPERIENCIA_LABORAL_TB E
JOIN FIDE_PERSONA_TB P
    ON P.CEDULA=E.CEDULA
JOIN FIDE_EMPRESA_TB EM
    ON E.ID_EMPRESA=EM.ID_EMPRESA
JOIN FIDE_CARGO_TB C
    ON E.ID_CARGO=C.ID_CARGO;
/
/*
AUTOR: JONATHAN PAEZ
FECHA: 14/11/25
VISTA PARA EL MODULO DE GESTION DOCENTE (EVALUACION DOCENTE)
*/
CREATE OR REPLACE VIEW FIDE_EVALUACION_DOCENTE_V AS
SELECT
    P.CEDULA,
    E.ID_TIPO_EVALUACION,
    T.DESCRIPCION AS EVALUACION,
    E.ANIO,
    E.CALIFICACION,
    E.COMENTARIOS,
    E.ID_ESTADO
FROM FIDE_EVALUACION_DOCENTE_TB E
JOIN FIDE_PERSONA_TB P
    ON E.CEDULA=P.CEDULA
JOIN FIDE_TIPO_EVALUACION_TB T
    ON E.ID_TIPO_EVALUACION=T.ID_TIPO_EVALUACION;
/
/*
AUTOR: JOY CHAVEZ
FECHA: 17/11/25
VISTA PARA EL MODULO DE MATRICULAS
*/
CREATE OR REPLACE VIEW FIDE_MATRICULAS_V AS
SELECT
    M.ID_MATRICULA,
    M.FECHA_MATRICULA,
    EM.DESCRIPCION AS ESTADO_MATRICULA,
    P.CEDULA AS CEDULA_APODERADO,
    P.NOMBRE || ' ' || P.APELLIDO_PATERNO || ' ' || P.APELLIDO_MATERNO AS APODERADO_NOMBRE_COMPLETO,
    I.CEDULA_INFANTE,
    I.NOMBRE || ' ' || I.APELLIDO_PATERNO || ' ' || I.APELLIDO_MATERNO AS INFANTE_NOMBRE_COMPLETO,
    F.ID_FACTURA,
    S.DESCRIPCION AS SERVICIO_DESCRIPCION,
    S.MONTO AS SERVICIO_MONTO,
    DF.MONTO_PAGADO AS SERVICIO_MONTO_PAGADO

FROM FIDE_MATRICULA_TB M
JOIN FIDE_INFANTE_TB I ON M.CEDULA_INFANTE = I.CEDULA_INFANTE
JOIN FIDE_PERSONA_TB P ON M.CEDULA = P.CEDULA
JOIN FIDE_ENCABEZADO_FACTURA_TB F ON M.ID_FACTURA = F.ID_FACTURA
JOIN FIDE_ESTADO_TB EM ON M.ID_ESTADO = EM.ID_ESTADO
JOIN FIDE_DETALLE_FACTURA_TB DF ON DF.ID_FACTURA = F.ID_FACTURA
JOIN FIDE_SERVICIO_TB S ON S.ID_SERVICIO = DF.ID_SERVICIO
WHERE S.DESCRIPCION = 'MATRICULA'
ORDER BY ID_MATRICULA;
/
/*
AUTOR: JOY CHAVEZ
FECHA: 17/11/25
VISTA PARA EL MODULO DE MENSUALIDADES
*/
CREATE OR REPLACE VIEW FIDE_MENSUALIDADES_V AS
SELECT
    M.ID_MENSUALIDAD,
    M.MES,
    E.DESCRIPCION AS ESTADO_MENSUALIDAD,
        P.CEDULA AS CEDULA_APODERADO,
    P.NOMBRE || ' ' || P.APELLIDO_PATERNO || ' ' || P.APELLIDO_MATERNO AS APODERADO_NOMBRE_COMPLETO,
    I.CEDULA_INFANTE,
    I.NOMBRE || ' ' || I.APELLIDO_PATERNO || ' ' || I.APELLIDO_MATERNO AS INFANTE_NOMBRE_COMPLETO,
    F.ID_FACTURA,
    S.DESCRIPCION AS SERVICIO_DESCRIPCION,
    S.MONTO AS SERVICIO_MONTO,
    DF.MONTO_PAGADO AS SERVICIO_MONTO_PAGADO

FROM FIDE_MENSUALIDAD_TB M
JOIN FIDE_INFANTE_TB I ON M.CEDULA_INFANTE = I.CEDULA_INFANTE
JOIN FIDE_PERSONA_TB P ON M.CEDULA = P.CEDULA
JOIN FIDE_ENCABEZADO_FACTURA_TB F ON M.ID_FACTURA = F.ID_FACTURA
JOIN FIDE_ESTADO_TB E ON M.ID_ESTADO = E.ID_ESTADO
JOIN FIDE_DETALLE_FACTURA_TB DF ON DF.ID_FACTURA = F.ID_FACTURA
JOIN FIDE_SERVICIO_TB S ON S.ID_SERVICIO = DF.ID_SERVICIO
WHERE S.DESCRIPCION = 'MENSUALIDAD'
ORDER BY ID_MENSUALIDAD;
/
/*
AUTOR: JOY CHAVEZ
FECHA: 18/11/25
VISTA PARA EL MODULO DE FACTURACION
*/
CREATE OR REPLACE VIEW FIDE_ENCABEZADO_FACTURA_V AS
SELECT
    EF.ID_FACTURA,
    EF.CEDULA AS CEDULA_APODERADO,
    P.NOMBRE || ' ' || P.APELLIDO_PATERNO || ' ' || P.APELLIDO_MATERNO AS APODERADO_NOMBRE_COMPLETO,
    EF.CEDULA_INFANTE,
    I.NOMBRE || ' ' || I.APELLIDO_PATERNO || ' ' || I.APELLIDO_MATERNO AS INFANTE_NOMBRE_COMPLETO,
    EF.FECHA_EMISION,
    EF.HORA_EMISION,
    EF.SUBTOTAL,
    EF.DESCUENTO,
    EF.IVA,
    EF.MONTO_TOTAL,
    MP.DESCRIPCION AS METODO_PAGO,
    E.DESCRIPCION AS ESTADO
FROM FIDE_ENCABEZADO_FACTURA_TB EF
JOIN FIDE_PERSONA_TB P ON EF.CEDULA = P.CEDULA
JOIN FIDE_INFANTE_TB I ON EF.CEDULA_INFANTE = I.CEDULA_INFANTE
JOIN FIDE_METODO_PAGO_TB MP ON EF.ID_METODO_PAGO = MP.ID_METODO_PAGO
JOIN FIDE_ESTADO_TB E ON EF.ID_ESTADO = E.ID_ESTADO
ORDER BY EF.ID_FACTURA; 
/
/*
AUTOR: JOY CHAVEZ
FECHA: 18/11/25
VISTA PARA EL MODULO DE FACTURACION
*/
CREATE OR REPLACE VIEW FIDE_DETALLE_FACTURA_V AS
SELECT
    DF.ID_FACTURA,
    DF.ID_SERVICIO,
    S.DESCRIPCION AS SERVICIO,
    DF.MONTO_PAGADO,
    E.DESCRIPCION AS ESTADO
FROM FIDE_DETALLE_FACTURA_TB DF
JOIN FIDE_SERVICIO_TB S ON DF.ID_SERVICIO = S.ID_SERVICIO
JOIN FIDE_ESTADO_TB E ON DF.ID_ESTADO = E.ID_ESTADO
ORDER BY ID_FACTURA;
/
/*
AUTOR: JOY CHAVEZ
FECHA: 20/11/25
VISTA PARA EL MODULO DE PAGOS
*/
CREATE OR REPLACE VIEW FIDE_PAGOS_V AS
SELECT 
    P.ID_PAGO,
    P.ID_FACTURA,
    EF.FECHA_EMISION,
    EF.CEDULA AS CEDULA_APODERADO,
    EF.CEDULA_INFANTE,
    P.MONTO_TOTAL,
    E.DESCRIPCION AS ESTADO
FROM FIDE_PAGO_TB P
JOIN FIDE_ENCABEZADO_FACTURA_TB EF ON P.ID_FACTURA = EF.ID_FACTURA
JOIN FIDE_ESTADO_TB E ON P.ID_ESTADO = E.ID_ESTADO
ORDER BY P.ID_PAGO;
/
/*
AUTOR: YEIK PACHECO
FECHA: 20/11/25
VISTA PARA EL MODULO DE CONTACTOS
*/
CREATE OR REPLACE VIEW FIDE_CONTACTOS_V AS
SELECT
    P.CEDULA,
    P.NOMBRE || ' ' || P.APELLIDO_PATERNO || ' ' || P.APELLIDO_MATERNO AS NOMBRE_COMPLETO,
    -- Correos activos (SIN duplicados)
    (
        SELECT LISTAGG(E.EMAIL, ', ') WITHIN GROUP (ORDER BY E.EMAIL)
        FROM FIDE_EMAIL_TB E
        WHERE E.CEDULA = P.CEDULA
          AND E.ID_ESTADO = 1
    ) AS EMAILS,
    -- Tel?fonos activos (SIN duplicados)
    (
        SELECT LISTAGG(T.NUM_TELEFONO, ', ') WITHIN GROUP (ORDER BY T.NUM_TELEFONO)
        FROM FIDE_TELEFONO_TB T
        WHERE T.CEDULA = P.CEDULA
          AND T.ID_ESTADO = 1
    ) AS TELEFONOS
FROM FIDE_PERSONA_TB P;
/
/*
AUTOR: SEBASTIAN SOLANO
FECHA: 27/11/25
VISTA PARA EL MODULO DE REPORTES
*/
CREATE OR REPLACE VIEW FIDE_REPORTE_FACTURAS_PADRE_V AS
SELECT
    F.ID_FACTURA,
    F.CEDULA AS CEDULA_PADRE,
    P.NOMBRE AS NOMBRE_PADRE,
    P.APELLIDO_PATERNO AS APE1_PADRE,
    P.APELLIDO_MATERNO AS APE2_PADRE,
    F.CEDULA_INFANTE,
    I.NOMBRE AS NOMBRE_INFANTE,
    I.APELLIDO_PATERNO AS APE1_INFANTE,
    I.APELLIDO_MATERNO AS APE2_INFANTE,
    F.FECHA_EMISION,
    F.HORA_EMISION,
    F.MONTO_TOTAL,
    F.SUBTOTAL,
    F.DESCUENTO,
    F.IVA,
    M.ID_MATRICULA,
    MEN.ID_MENSUALIDAD,
    MEN.MES AS MES_MENSUALIDAD,  
    MEN.ID_ESTADO AS ESTADO_MENSUALIDAD
FROM FIDE_ENCABEZADO_FACTURA_TB F
LEFT JOIN FIDE_PERSONA_TB P
    ON P.CEDULA = F.CEDULA
LEFT JOIN FIDE_INFANTE_TB I
    ON I.CEDULA_INFANTE = F.CEDULA_INFANTE
LEFT JOIN FIDE_MATRICULA_TB M
    ON M.ID_FACTURA = F.ID_FACTURA
LEFT JOIN FIDE_MENSUALIDAD_TB MEN
    ON MEN.ID_FACTURA = F.ID_FACTURA;
/
/*
AUTOR: SEBASTIAN SOLANO
FECHA: 27/11/25
VISTA PARA EL MODULO DE REPORTES
*/
CREATE OR REPLACE VIEW FIDE_REPORTE_ASISTENCIA_V AS
SELECT
    A.CEDULA_INFANTE,
    I.NOMBRE,
    I.APELLIDO_PATERNO,
    I.APELLIDO_MATERNO,
    A.FECHA,
    A.HORA_ENTRADA,
    A.HORA_SALIDA,
    A.OBSERVACIONES,
    A.ID_ESTADO
FROM FIDE_ASISTENCIA_TB A
LEFT JOIN FIDE_INFANTE_TB I
    ON I.CEDULA_INFANTE = A.CEDULA_INFANTE;
/
/*
AUTOR: SEBASTIAN SOLANO
FECHA: 27/11/25
VISTA PARA EL MODULO DE REPORTES
*/
CREATE OR REPLACE VIEW FIDE_REPORTE_MATRICULAS_V AS
SELECT
    M.ID_MATRICULA,
    M.FECHA_MATRICULA,
    M.CEDULA AS CEDULA_PADRE,
    P.NOMBRE AS NOMBRE_PADRE,
    P.APELLIDO_PATERNO AS APE1_PADRE,
    P.APELLIDO_MATERNO AS APE2_PADRE,
    M.CEDULA_INFANTE,
    I.NOMBRE AS NOMBRE_INFANTE,
    I.APELLIDO_PATERNO AS APE1_INFANTE,
    I.APELLIDO_MATERNO AS APE2_INFANTE,
    M.ID_FACTURA
FROM FIDE_MATRICULA_TB M
LEFT JOIN FIDE_PERSONA_TB P
    ON P.CEDULA = M.CEDULA
LEFT JOIN FIDE_INFANTE_TB I
    ON I.CEDULA_INFANTE = M.CEDULA_INFANTE;
/
/*
AUTOR: SEBASTIAN SOLANO
FECHA: 27/11/25
VISTA PARA EL MODULO DE REPORTES
*/
CREATE OR REPLACE VIEW FIDE_REPORTE_ACTIVIDADES_V AS
SELECT
    A.ID_ACTIVIDAD,
    A.DESCRIPCION AS ACTIVIDAD,
    A.FECHA,
    A.HORA,
    A.OBSERVACIONES,
    C.CEDULA_INFANTE,
    I.NOMBRE AS NOMBRE_INFANTE,
    I.APELLIDO_PATERNO AS APE1_INFANTE,
    I.APELLIDO_MATERNO AS APE2_INFANTE,
    C.CALIFICACION,
    C.OBSERVACIONES AS OBS_CALIFICACION
FROM FIDE_ACTIVIDAD_TB A
LEFT JOIN FIDE_CALIFICACION_TB C
    ON C.ID_ACTIVIDAD = A.ID_ACTIVIDAD
LEFT JOIN FIDE_INFANTE_TB I
    ON I.CEDULA_INFANTE = C.CEDULA_INFANTE;
/
/*
AUTOR: SEBASTIAN SOLANO
FECHA: 27/11/25
VISTA PARA EL MODULO DE REPORTES
*/
CREATE OR REPLACE VIEW FIDE_REPORTE_DOCENTE_V AS
SELECT
    D.CEDULA AS CEDULA_DOCENTE,
    D.NOMBRE AS NOMBRE_DOCENTE,
    D.APELLIDO_PATERNO AS APE1_DOCENTE,
    D.APELLIDO_MATERNO AS APE2_DOCENTE,
    AG.ID_ACTIVIDAD,
    A.DESCRIPCION AS ACTIVIDAD,
    A.FECHA,
    A.HORA,
    A.OBSERVACIONES AS OBS_ACTIVIDAD,
    E.ANIO AS ANIO_EVALUACION,
    E.CALIFICACION AS CALIFICACION_DOCENTE,
    E.COMENTARIOS AS COMENTARIOS_DOCENTE
FROM FIDE_GRUPO_TB G
LEFT JOIN FIDE_PERSONA_TB D
    ON D.CEDULA = G.CEDULA
LEFT JOIN FIDE_ACTIVIDAD_POR_GRUPO_TB AG
    ON AG.ID_GRUPO = G.ID_GRUPO
LEFT JOIN FIDE_ACTIVIDAD_TB A
    ON A.ID_ACTIVIDAD = AG.ID_ACTIVIDAD
LEFT JOIN FIDE_EVALUACION_DOCENTE_TB E
    ON E.CEDULA = G.CEDULA;
/
/*
AUTOR: SEBASTIAN SOLANO
FECHA: 27/11/25
VISTA PARA EL MODULO DE REPORTES
*/
CREATE OR REPLACE VIEW FIDE_REPORTE_RESUMEN_PADRE_V AS
SELECT
    I.CEDULA_INFANTE,
    I.NOMBRE AS NOMBRE_INFANTE,
    I.APELLIDO_PATERNO AS APE1_INFANTE,
    I.APELLIDO_MATERNO AS APE2_INFANTE,
    A.FECHA AS FECHA_ASISTENCIA,
    A.HORA_ENTRADA,
    A.HORA_SALIDA,
    A.ID_ESTADO AS ESTADO_ASISTENCIA,
    A.OBSERVACIONES AS OBS_ASISTENCIA,
    F.ID_FACTURA,
    F.FECHA_EMISION,
    F.MONTO_TOTAL,
    F.SUBTOTAL,
    F.DESCUENTO,
    F.IVA,
    AC.ID_ACTIVIDAD,
    ACT.DESCRIPCION AS ACTIVIDAD,
    AC.CALIFICACION,
    AC.OBSERVACIONES AS OBS_CALIFICACION
FROM FIDE_INFANTE_TB I
LEFT JOIN FIDE_ASISTENCIA_TB A
    ON A.CEDULA_INFANTE = I.CEDULA_INFANTE
LEFT JOIN FIDE_ENCABEZADO_FACTURA_TB F
    ON F.CEDULA_INFANTE = I.CEDULA_INFANTE
LEFT JOIN FIDE_CALIFICACION_TB AC
    ON AC.CEDULA_INFANTE = I.CEDULA_INFANTE
LEFT JOIN FIDE_ACTIVIDAD_TB ACT
    ON ACT.ID_ACTIVIDAD = AC.ID_ACTIVIDAD;