--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_ESTADO_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_PAIS_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_PROVINCIA_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_CANTON_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_DISTRITO_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_ROL_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_PERSONA_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_DIRECCION_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_USUARIO_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_EMAIL_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_TELEFONO_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_CATEGORIA_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_INSTITUCION_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_FORMACION_ACADEMICA_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_TEMA_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_PROVEEDOR_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_CAPACITACION_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_EMPRESA_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_CARGO_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_EXPERIENCIA_LABORAL_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_TIPO_EVALUACION_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_EVALUACION_DOCENTE_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_INFANTE_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_ALERGIA_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_VACUNA_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_MEDICAMENTO_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_TUTORES_INFANTES_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_ASISTENCIA_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_GRUPO_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_DETALLE_GRUPO_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_INFANTES_ALERGIAS_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_INFANTES_VACUNAS_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_INFANTES_MEDICAMENTOS_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_ACTIVIDAD_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_ACTIVIDAD_POR_GRUPO_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_CALIFICACION_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_ENCABEZADO_FACTURA_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_DETALLE_FACTURA_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_MATRICULA_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_MENSUALIDAD_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_PAGO_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_METODO_PAGO_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);
/
--AUTOR: YEIK PACHECO
--FECHA: 3/12/2025
--ALTER PARA AUDITORIA
ALTER TABLE FIDE_SERVICIO_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ACCION VARCHAR2(100)
);